#!/bin/sh
# Live's arithmetic on a laptop: the interval clamp, the capped backoff, the
# clock plausibility floor and the one wake rule.
#
#   host-tests/live/run.sh
#
# Nothing here touches a card, a radio or a panel, which is the point: the
# failure the backoff exists to prevent is a battery three weeks out, and the
# due-now rule only misbehaves on the sleep AFTER the one you were watching.
# Neither is observable by looking at a device.
set -e
cd "$(dirname "$0")"
BUILD_DIR="${TMPDIR:-/tmp}/$(basename "${CXX:-c++}")-live-tests-$(cd ../.. && pwd | cksum | cut -d" " -f1)"
mkdir -p "$BUILD_DIR"

# THE SERVICE'S THREE NUMBERS, read out of the service rather than typed here.
#
# The reader holds a copy of all three: the clamp it applies to X-Next-Wake and
# the interval it seeds itself with before the service has ever spoken. They are
# two copies of one fact and one of them drifted -- six hours against a day --
# and nothing anywhere could have noticed, because neither side had the other's
# number. Generated, so a change on either side fails this run.
python3 - ../../server/fridge-bridge/bridge/store.py > "$BUILD_DIR/service_limits.generated.h" <<'PY'
import ast
import sys

tree = ast.parse(open(sys.argv[1]).read())
want = {"DEFAULT_INTERVAL_S", "MIN_INTERVAL_S", "MAX_INTERVAL_S"}
found = {}
for node in tree.body:
    if not isinstance(node, ast.Assign):
        continue
    for target in node.targets:
        if isinstance(target, ast.Name) and target.id in want:
            found[target.id] = int(eval(compile(ast.Expression(node.value), "<s>", "eval"), {}, {}))
missing = want - set(found)
if missing:
    sys.exit("live: store.py no longer defines %s, so the reader's copy is unchecked" % ", ".join(sorted(missing)))

print("// Generated by host-tests/live/run.sh from server/fridge-bridge/bridge/store.py.")
for name, value in sorted(found.items()):
    print("constexpr long kService%s = %d;" % (name.title().replace("_", ""), value))
PY

"${CXX:-c++}" -std=c++17 -O1 -Wall -Wextra -Werror -I"$BUILD_DIR" \
  ../../src/apps_local/live/LiveCore.cpp \
  test_live.cpp -o "$BUILD_DIR/test_live"
"$BUILD_DIR/test_live"

# EVERY WAY INTO DEEP SLEEP CARRIES LIVE'S ALARM (card #620).
#
# The arithmetic above is worth nothing if a sleep path does not call it, and
# that is exactly how Mario's fridge missed its 02:00: two re-sleep paths in
# main.cpp armed kTimerWakeMicros, which is 0 on every release env, and one
# bump disarmed Live. main.cpp cannot link on a laptop, so it is read. Every
# startDeepSleepArmed() call must pass Live's number: enterDeepSleep's
# timerMicros, the timer wake's nextWake, or resleepTimerMicros(). A bare
# kTimerWakeMicros is the bug.
python3 - ../../src/main.cpp <<'PY'
import re
import sys

# Comments stripped first, so a sentence naming the call is not read as one;
# braces excluded, so the definition is not read as a call.
src = re.sub(r"//[^\n]*", "", open(sys.argv[1]).read())
calls = re.findall(r"startDeepSleepArmed\(([^;{}]*)\);", src)
bad = [c for c in calls if c.strip() == "kTimerWakeMicros"]
fails = 0
if len(calls) != 4:
    print("FAIL live  found %d startDeepSleepArmed calls in main.cpp, expected 4 (enterDeepSleep, the timer wake, and the two re-sleeps); read the new one and add it here" % len(calls))
    fails += 1
for c in bad:
    print("FAIL live  main.cpp sleeps with startDeepSleepArmed(%s): 0 on a release build, so Live's alarm is dropped (card #620)" % c.strip())
    fails += 1
allowed = ("timerMicros", "resleepTimerMicros()", "nextWake")
for c in calls:
    if c.strip() in bad:
        continue
    if not any(a in c for a in allowed):
        print("FAIL live  main.cpp sleeps with startDeepSleepArmed(%s), which is not Live's number" % c.strip())
        fails += 1
m = re.search(r"resleepTimerMicros\(\)\s*\{(.*?)\n\}", src, re.S)
if not m or "live::engine::resleepSeconds()" not in m.group(1):
    print("FAIL live  resleepTimerMicros() no longer asks live::engine::resleepSeconds()")
    fails += 1
print("live-sleep-paths: %d calls, %d failed" % (len(calls), fails))
sys.exit(1 if fails else 0)
PY
