#!/bin/sh
# Walks every built-in wallpaper name and the "+ Add" tile through the picker's
# real geometry and the real toybox cuts, and fails if the selection marker can
# touch the artwork or a caption in any grid position.
#
#   host-tests/wallcaption/run.sh
#
# Links lib/EpdFont and the generated font headers on purpose: host-tests/ui
# measures ten pixels a character, which cannot see a caption overflow a 165px
# cell in a real face.
set -e
cd "$(dirname "$0")"
BUILD_DIR="${TMPDIR:-/tmp}/$(basename "${CXX:-c++}")-wallcaption-tests-$(cd ../.. && pwd | cksum | cut -d" " -f1)"
mkdir -p "$BUILD_DIR"
# THE SERVICE'S OWN SENTENCES, extracted from the service rather than copied.
#
# The Live screen draws a bridge refusal verbatim -- the device does not get to
# reword a decision somebody else made -- so the strings that have to fit its
# report region are refused() calls in server/fridge-bridge/bridge/app.py, not
# strings anyone types here. A list typed into the test would keep measuring the
# old sentences after the service edited one, and stay green while the panel cut
# the new one (derived-facts-written-as-literals). So it is generated, every run.
APP=../../server/fridge-bridge/bridge/app.py
GEN="$BUILD_DIR/service_refusals.generated.h"
{
  echo '// Generated by host-tests/wallcaption/run.sh from server/fridge-bridge/bridge/app.py.'
  echo 'static const char* kServiceRefusals[] = {'
  # f-strings interpolate the cap; MAX_SENDERS is 4, substituted so the string
  # measured is the string sent.
  sed -n 's/.*refused(f\{0,1\}"\([^"]*\)".*/\1/p' "$APP"     | sed 's/{store.MAX_SENDERS}/4/g'     | grep -v '{'     | sort -u     | sed 's/.*/  "&",/'
  echo '};'
} > "$GEN"

SDK=../../freeink-sdk/libs/ui/FreeInkUI
ICONS=../../freeink-sdk/libs/assets/Icons
SRC=../../src/apps_local/wallpapers
"${CXX:-c++}" -std=c++17 -O1 -Wall -Wextra -Werror -Wno-comment -Wno-missing-field-initializers \
  -I"$BUILD_DIR" -I"$SDK/include" -I"$ICONS/include" -I../../lib/EpdFont -I../../lib/Utf8 \
  "$SDK/src/FreeInkUI.cpp" \
  $SRC/WallpapersCore.cpp $SRC/WallpapersScreens.cpp \
  ../../lib/EpdFont/EpdFont.cpp ../../lib/EpdFont/EpdFontFamily.cpp ../../lib/Utf8/Utf8.cpp \
  test_wallcaption.cpp -o "$BUILD_DIR/test_wallcaption"
"$BUILD_DIR/test_wallcaption"
