#!/usr/bin/env python3
"""Import a third-party nonogram corpus into pictures.txt format.

This exists because the pictures a person enjoys solving are DESIGNED, and
designing them is the one part of a nonogram nobody can automate: a generated
grid that happens to be unique and line-solvable is still, almost always, an
unreadable blob. So the interesting corpora are collections somebody drew and
somebody else played -- and every one of those is third-party work.

  python3 tools_local/picross/import_picross.py \\
      --corpus <file> --format janko-json --sizes 10,15 \\
      --author-map janko_authors.json \\
      --license 'all rights reserved' --source-template \\
        'https://www.janko.at/Raetsel/Nonogramme/{id}.a.htm' \\
      --out /tmp/corpus.txt   # OUTSIDE the tree: see the write guard below

WHAT THIS SCRIPT WILL NOT DO. It will not write a corpus into this repository
unless its licence is one of REDISTRIBUTABLE below. That is not a formality:
an imported puzzle whose licence is unstated is ALL RIGHTS RESERVED, and the
moment it lands in assets_local/ it is in a public repository, in every clone,
and in every release binary. Evaluating one locally is fine and is what this
script is for; shipping one is a permission somebody has to actually obtain.
The refusal is here rather than in a review checklist because a checklist is
not a mechanism.

THE GATE IS NOT REIMPLEMENTED HERE. `evaluate` is imported from gen_picross,
so an imported puzzle faces exactly the test a hand-drawn one faces: unique,
line-solvable, and filling its grid. A second copy of that gate would be a
second thing to keep in step, and the copy that drifts is always the one
nobody runs.

NAMES. A corpus that TITLES its puzzles is titled here, verbatim, case and all,
and that title becomes the puzzle's identity and the string the win screen
reveals. Most corpora have no titles at all -- janko's certainly does not -- and
this writes `<prefix><id>` when there is nothing better. That is deliberate
and it is safe: the picross app shows a puzzle's name ONLY on the win screen,
after the picture is revealed (PicrossScreens::buildWin). The picker shows a
number and a size for an unsolved puzzle and the finished picture for a solved
one, so a name can neither spoil a reveal nor help a player choose. A catalogue
number is a poor punchline, though, which is a quality cost worth stating out
loud rather than a correctness one.
"""

import argparse
import json
import os
import re
import signal
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

from gen_picross import SIZES, evaluate  # noqa: E402  (path set above)

# Licences whose puzzles may be written into this repository. Anything else is
# evaluated locally and stays out of git. Spelled as the lowercase forms this
# script compares against, so "CC0-1.0" and "cc0-1.0" both pass.
REDISTRIBUTABLE = (
    "cc0-1.0",
    "cc-by-4.0",
    "cc-by-sa-4.0",
    "public domain",
    "mit",
)

# Two banners, because the file means different things in the two cases and a
# reader opening it has only the banner to go on. The evaluation banner says
# "delete me"; the permitted one says whose permission this rests on and where
# the record is. Writing the second one when there is no permission is the
# failure this whole script exists to prevent, so it is chosen by the same
# `--permission` the write guard is.
BANNER = """# GENERATED by tools_local/picross/import_picross.py -- DO NOT COMMIT.
#
# These puzzles are THIRD-PARTY WORK under the licence recorded below. They are
# here to be evaluated locally: rendered, solved, judged. Redistributing them
# (committing this file, shipping a bank built from it, publishing a release
# that contains it) needs the author's permission first, which nobody has yet.
#
# Corpus:  %(corpus)s
# Licence: %(license)s
# Puzzles: %(count)d
"""

PERMITTED_BANNER = """# GENERATED by tools_local/picross/import_picross.py. Do not edit by hand.
#
# These puzzles are THIRD-PARTY WORK, used BY PERMISSION and not under a public
# licence. The permission is recorded in %(permission)s -- read it before you
# copy anything out of this file. It was granted to this project; a fork of this
# repository does NOT inherit it.
#
# Each puzzle carries its own author and its own source URL, so the credit
# survives a merge, a re-sort and a partial copy in a way a paragraph does not.
#
# Corpus:  %(corpus)s
# Licence: %(license)s
# Puzzles: %(count)d
#
# The command that regenerates this file is in docs/apps/picross.md. The corpus
# is named here by FILE rather than by the path it was read from: that path is
# whichever scratch directory the importing session happened to use, and a
# committed file pointing at somebody's /tmp is worse than one that does not
# pretend to know.
"""

UNATTRIBUTED_BANNER = """# GENERATED by tools_local/picross/import_picross.py. Do not edit by hand.
#
# THESE PUZZLES CARRY NO ATTRIBUTION, and that is a settled fact rather than a
# gap somebody forgot to fill. There is nobody to credit, no licence to honour
# and no source to cite, so none of the three is written: no @author line and no
# @source line appears below at all, and the file-level @license reads `unknown`
# because that is the true value.
#
# DO NOT "FIX" THIS by finding an origin to name. The reason is
# %(reason)s
# and it is Mario's decision. A hedged source line, a TODO, or a guess would all
# be worse than the silence, because each one invites the next reader to resolve
# it.
#
# WHAT IS TRUE, and the one thing worth carrying: the bank is NOT public domain
# and NOT this fork's own work. CrossPlay's code is MIT and a fork inherits
# that; these puzzles came to the project privately and are not ours to
# relicense, republish, or offer as a downloadable pack. That sentence exists
# because the opposite mistake has been made here before -- 68 puzzles were once
# described as CC0 that were not ours to describe at all.
#
# THE CORPUS IS NOT NAMED HERE EITHER, and that is the same decision one step
# further. The other two banners print the file they were built from, which is
# ordinary provenance; here the filename is the only surviving string that says
# where the pack came from, eighteen lines under a paragraph promising there is
# no source to cite. A filename is a smaller claim than a URL and it is still a
# claim.
#
# Licence: %(license)s
# Puzzles: %(count)d
"""


def parse_janko_json(path, sizes):
    """Yield (id, size, cells, title) from the puzzlekit Nonogram dataset.

    `title` is always None here: janko's corpus carries no titles at all, which
    is why --name-prefix exists and why the names in that bank were a catalogue
    id until somebody typed a real one.

    Keys look like '1051_10x10'; the number is the janko puzzle number, which
    is what its page URL and its author record are keyed by. `solution` is a
    'H W' line then rows of 'x' (solid) and '-' (empty), space separated.
    """
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    data = (
        payload["data"] if isinstance(payload, dict) and "data" in payload else payload
    )
    for key in sorted(data, key=_natural):
        shape = re.search(r"^(.+?)_(\d+)x(\d+)$", key)
        if not shape:
            continue
        ident, width, height = shape.group(1), int(shape.group(2)), int(shape.group(3))
        if width != height or width not in sizes:
            continue
        solution = data[key].get("solution")
        if not solution:
            continue
        rows = solution.strip().split("\n")[1:]  # drop the 'H W' header line
        cells = [[1 if token == "x" else 0 for token in row.split()] for row in rows]
        if len(cells) != height or any(len(row) != width for row in cells):
            continue
        yield ident, width, cells, None


def parse_nonogram_pack(path, sizes):
    """Yield (id, size, cells, title) from a nonogram-pack `nonograms_all.json`.

    The pack is an object keyed by tier ("5x5" .. "10x10"), each holding records
    with `id`, `title`, `size` and a `solution` of one string per row, '1' solid.

    IT IS READ FOR THE SOLUTION ONLY. The pack also carries `row_clues`,
    `col_clues` and a `line_solvable` flag, and none of the three is read here:
    the clues are DERIVED from the picture by gen_picross (so they cannot
    disagree with it) and line-solvability is PROVED by our own gate rather than
    believed from a field. A flag saying a puzzle is fine is not the same fact
    as this repository having checked, and the whole point of the gate is that
    the two are told apart.

    The pack DOES carry titles, and they are the puzzle's identity here -- see
    --name-prefix, which this format does not need.
    """
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        sys.exit("%s is not an object keyed by tier ('5x5', '10x10', ...)" % path)
    records = []
    for tier in sorted(payload, key=_natural):
        group = payload[tier]
        if not isinstance(group, list):
            continue
        records.extend(group)
    for record in sorted(records, key=lambda r: _natural(str(r.get("id", "")))):
        rows = record.get("solution")
        if not rows:
            continue
        size = int(record.get("size") or len(rows))
        if size not in sizes:
            continue
        cells = [[1 if ch == "1" else 0 for ch in row] for row in rows]
        if len(cells) != size or any(len(row) != size for row in cells):
            continue
        title = str(record.get("title") or "").strip() or None
        yield str(record.get("id", "")), size, cells, title


def parse_non_dir(path, sizes):
    """Yield (id, size, cells, title) from a directory of .non files.

    The .non format stores CLUES rather than a solution, so a corpus in it
    cannot be imported without solving every puzzle first. Rather than grow a
    solver here, this reports what it found and asks for a solved corpus:
    guessing at a solution is exactly how a bank ends up with a puzzle whose
    picture nobody has ever seen.
    """
    del sizes
    count = sum(1 for entry in os.listdir(path) if entry.endswith(".non"))
    sys.exit(
        "%s holds %d .non files, which carry clues and no solution. Import a "
        "corpus that stores solved grids, or solve them first -- this script "
        "will not invent a picture from clues." % (path, count)
    )


FORMATS = {
    "janko-json": parse_janko_json,
    "nonogram-pack": parse_nonogram_pack,
    "non-dir": parse_non_dir,
}


# A permission record has to SAY these things before it counts. The check is
# deliberately about the shape of the record rather than its prose: it cannot
# tell whether a permission is real, only whether somebody wrote down who
# granted it, to whom, when, and that it is not a public licence. That last one
# is the load-bearing line -- a reader of a public repository will otherwise
# assume a fork inherits the right, and it does not.
PERMISSION_MUST_MENTION = (
    ("who granted it", ("granted by", "permission from", "permission was obtained")),
    (
        "that it is not a licence",
        ("not a licence", "not a license", "no public licence", "no public license"),
    ),
    (
        "that it does not travel to forks",
        ("does not extend", "does not transfer", "not inherited", "do not inherit"),
    ),
)

# The date is a PATTERN, not a needle. It was the substring "20", which the
# record it guards satisfies with the words "20x20" and "217px" -- so a
# permission file with every date stripped out of it passed, and the check that
# the docs describe as requiring "when" required nothing at all. An ISO date is
# the one form that cannot be a measurement.
PERMISSION_DATE = re.compile(r"\b(?:19|20)\d\d-\d\d-\d\d\b")


def check_permission(ref):
    """None if `ref` cites a real, sufficiently specific permission record.

    Otherwise a sentence saying what is missing. The guard opens because a
    permission is RECORDED IN THE REPOSITORY, never because it was waived on the
    command line: the file has to exist and has to say the things a reader needs
    in order not to be misled. The next corpus faces the same check.
    """
    if not ref:
        return "No --permission given."
    path = ref if os.path.isabs(ref) else os.path.join(ROOT, ref)
    path = os.path.abspath(path)
    if not path.startswith(ROOT + os.sep):
        return "--permission must cite a file inside this repository, so the record ships with the data."
    if not os.path.exists(path):
        return "--permission cites %s, which does not exist." % ref
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read().lower()
    except OSError as exc:
        return "--permission cites %s, which could not be read (%s)." % (ref, exc)
    missing = [
        label
        for label, needles in PERMISSION_MUST_MENTION
        if not any(n in text for n in needles)
    ]
    if not PERMISSION_DATE.search(text):
        missing.append("a date (YYYY-MM-DD)")
    if missing:
        return (
            "%s does not record %s. A permission record has to state who granted it, "
            "that it is not a public licence, that it does not extend to forks, and when."
            % (ref, ", ".join(missing))
        )
    return None


def load_selection(path):
    """The set of corpus ids a curated import keeps, as strings.

    A curated list exists because the gate CANNOT SEE THE PICTURE. Unique,
    line-solvable and fills-its-grid are properties of the CLUES; a puzzle can
    satisfy all three and still solve into a scatter of blobs nobody can name.
    Whether the finished picture is legible is a judgement somebody makes by
    looking, and the only place to keep that judgement is a list of ids.

    Returned as {(size_or_None, id)}, and the SIZE is half the key whenever the
    file carries one. A corpus keyed `<id>_<W>x<H>` can hold the same number at
    two sizes -- janko does -- so a flat set of numbers would import a puzzle at
    a size nobody judged, which is exactly the puzzle the curation exists to
    keep out. A group named "10x10" or "10" pins its ids to that size; a flat
    list pins nothing and matches any size.

    Accepts a flat JSON list, a JSON object whose values are lists (so the
    judgement can stay grouped by size, which is how it was made), or a plain
    text file of one id per line. Ids are compared as strings, because a corpus
    key is a string and "0222" and "222" are different keys. Keys beginning with
    "_" are notes, not groups.
    """
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    try:
        payload = json.loads(text)
    except ValueError:
        return {
            (None, line.strip())
            for line in text.splitlines()
            if line.strip() and not line.startswith("#")
        }
    if isinstance(payload, dict):
        payload = payload.get("keep", payload)
    if isinstance(payload, dict):
        chosen = set()
        for group, value in payload.items():
            if group.startswith("_") or not isinstance(value, list):
                continue
            match = re.match(r"^(\d+)(?:x\1)?$", str(group))
            size = int(match.group(1)) if match else None
            chosen.update((size, str(v)) for v in value)
        return chosen
    if isinstance(payload, list):
        return {(None, str(v)) for v in payload}
    sys.exit("%s is not a list of ids, an object of lists, or one id per line." % path)


def author_of(record, fallback):
    """The author named by one --author-map entry, whatever shape it is in.

    A crawl writes {"author": ..., ...}; an older hand-written map writes a
    list whose first element is the author. Both are read rather than one being
    declared correct, because the alternative is a silent fallback to
    "unknown" -- and "unknown" is the one value that must never be wrong here:
    it denies credit to a named person whose permission this import rests on.
    """
    if isinstance(record, dict):
        return record.get("author") or fallback
    if isinstance(record, (list, tuple)) and record:
        return record[0]
    if isinstance(record, str) and record:
        return record
    return fallback


class GateTimeout(Exception):
    pass


def gated(name, cells, seconds):
    """evaluate() with a wall-clock ceiling, or (None, why) when it runs over.

    The gate is NOT changed by this -- it is the same evaluate(), reaching the
    same verdict -- but a corpus is not a hand-drawn batch of twenty, and its
    cost per puzzle spans orders of magnitude. `count_solutions` is exhaustive,
    and a handful of grids in any large collection send it into the hundreds of
    seconds. Waiting is pointless: a puzzle that expensive to prove is one this
    bank can simply not take, and the alternative to a ceiling is an import that
    looks hung with nothing to read.

    Reported as its own outcome rather than folded into a failure, because
    "too slow to decide" and "decided against" are different facts.
    """
    if seconds <= 0:
        return evaluate(name, cells)

    def ring(_signum, _frame):
        raise GateTimeout()

    previous = signal.signal(signal.SIGALRM, ring)
    signal.setitimer(signal.ITIMER_REAL, seconds)
    try:
        return evaluate(name, cells)
    except GateTimeout:
        return None, "gate did not finish within %gs" % seconds
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, previous)


def _natural(key):
    """Sort '9_15x15' before '1051_10x10' rather than after it."""
    return [int(part) if part.isdigit() else part for part in re.split(r"(\d+)", key)]


def format_source(template, ident):
    """Fill a source-URL template for one puzzle id.

    `{id}` is the id as it appears in the corpus; `{id04}` is it zero-padded to
    four digits. Both exist because janko serves its low-numbered puzzles ONLY
    padded -- `/Nonogramme/1.a.htm` is a 404 and `/Nonogramme/0001.a.htm` is the
    page -- so a template using `{id}` alone writes a dead link for every puzzle
    numbered under 1000. A provenance URL that 404s is worse than none: it looks
    like the origin was recorded and checked.
    """
    if not template:
        return ""
    try:
        padded = "%04d" % int(ident)
    except (TypeError, ValueError):
        padded = str(ident)
    return template.format(id=ident, id04=padded)


def render(cells):
    return "\n".join("".join("#" if v else "." for v in row) for row in cells)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--corpus", required=True, help="corpus file or directory")
    ap.add_argument("--format", required=True, choices=sorted(FORMATS))
    ap.add_argument("--out", required=True, help="pictures.txt-format file to write")
    ap.add_argument(
        "--license",
        required=True,
        help="the corpus licence. Unstated means all rights reserved; say that.",
    )
    ap.add_argument("--author", default="unknown", help="fallback author")
    ap.add_argument(
        "--author-map",
        help="JSON mapping a corpus id to its author, overriding --author per "
        'puzzle. The value may be the name itself, {"author": name}, or '
        "[author, ...]; keys beginning with _ are ignored as notes.",
    )
    ap.add_argument(
        "--source-template",
        default="",
        help="per-puzzle source URL; {id} is the corpus id, {id04} zero-pads it to "
        "four digits (janko serves low ids only in padded form)",
    )
    ap.add_argument("--name-prefix", default="", help="name is <prefix><id>")
    ap.add_argument(
        "--rename",
        default="",
        help="JSON {corpus title: our title}, applied to titled corpora. A corpus "
        "title is somebody else's copy and occasionally it does not fit the "
        "panel or is not what Mario wants revealed; this records the change in "
        "the tree so a re-import reproduces the same bank instead of quietly "
        "putting the original back. Every key must match a title actually seen, "
        "or the run fails -- a rename that matches nothing is a rename that "
        "silently did not happen.",
    )
    ap.add_argument(
        "--sizes",
        default=",".join(str(s) for s in SIZES),
        help="comma-separated board sizes to keep",
    )
    ap.add_argument("--limit", type=int, default=0, help="stop after N passes")
    ap.add_argument(
        "--ids",
        help="file of corpus ids to keep -- the curated selection. Without it the "
        "whole corpus is imported, which ships every puzzle that passes the "
        "gate including the ones that solve into noise.",
    )
    ap.add_argument(
        "--permission",
        default="",
        help="path (inside the repo) to the record of the permission that allows "
        "redistributing this corpus. Required to write a non-redistributable "
        "corpus into the tree; the record must name who granted it, say it is "
        "not a public licence, say it does not extend to forks, and be dated.",
    )
    ap.add_argument(
        "--unattributed",
        default="",
        metavar="REASON",
        help="a one-line statement of WHY this corpus carries no attribution, "
        "written into the file's banner. Use it only when there is genuinely "
        "nobody to credit and no licence to honour -- not as a way past "
        "--permission for a corpus that has an author somebody could have "
        "asked. It writes author and licence as 'unknown', writes no source "
        "URL, and states in the banner that the puzzles are neither public "
        "domain nor this fork's own work.",
    )
    ap.add_argument(
        "--gate-timeout",
        type=float,
        default=20.0,
        help="seconds to spend proving one puzzle before giving up on it (0 = forever)",
    )
    args = ap.parse_args()

    sizes = tuple(int(part) for part in args.sizes.split(",") if part.strip())
    unknown = [s for s in sizes if s not in SIZES]
    if unknown:
        sys.exit("sizes %r are not tiers the app has (%r)" % (unknown, list(SIZES)))

    out = os.path.abspath(args.out)
    inside_repo = out.startswith(ROOT + os.sep)
    free = args.license.strip().lower() in REDISTRIBUTABLE
    unattributed = args.unattributed.strip()

    # An UNATTRIBUTED import states nothing, so it may not be dressed up as
    # either of the other two. A licence that is not literally "unknown" is a
    # claim; a --permission beside it records a permission from nobody; an
    # --author-map or a --source-template beside it names the very things this
    # flag says do not exist. All four are refused rather than quietly ignored,
    # because a flag that tolerates a claim next to it is how "there is nothing
    # to cite" turns back into a citation.
    if unattributed:
        if args.license.strip().lower() != "unknown":
            sys.exit(
                "--unattributed goes with --license unknown and nothing else; %r is a "
                "claim about origin, and an unattributed import has none to make."
                % args.license
            )
        # --author is the fourth author-bearing flag and it was the one this
        # check missed. It is inert (the @author write is skipped below), which
        # is exactly why it is worth refusing: a flag that is silently ignored
        # reads to the next person as a flag that worked.
        if args.permission or args.author_map or args.source_template or args.author != "unknown":
            sys.exit(
                "--unattributed means there is nobody to credit and nothing to cite, so "
                "--permission, --author, --author-map and --source-template all contradict "
                "it. A corpus with an author to name is not unattributed; it is unasked."
            )

    if inside_repo and not free and not unattributed:
        permission_error = check_permission(args.permission)
        if permission_error:
            sys.exit(
                "refusing to write %s inside this repository under licence %r.\n"
                "%s\n"
                "Third-party puzzles are all rights reserved until somebody obtains\n"
                "permission, and a file in the repo is a file in every clone and every\n"
                "release. Evaluate it outside the tree (a scratch directory) instead,\n"
                "or record the permission first and cite it with --permission.\n"
                "If there is genuinely nobody to credit and no licence to honour, say so\n"
                "with --unattributed '<why>' -- which claims nothing and cites nothing."
                % (os.path.relpath(out, ROOT), args.license, permission_error)
            )

    authors = {}
    if args.author_map:
        with open(args.author_map, encoding="utf-8") as handle:
            authors = json.load(handle)

    chosen = load_selection(args.ids) if args.ids else None
    if chosen is not None:
        print("curated selection: %d ids from %s" % (len(chosen), args.ids))

    renames = {}
    if args.rename:
        with open(args.rename, encoding="utf-8") as handle:
            renames = {
                k: v for k, v in json.load(handle).items() if not k.startswith("_")
            }
        print("%d title overrides from %s" % (len(renames), args.rename))
    renames_used = set()

    kept = []
    skipped_unchosen = 0
    found = set()
    reasons = {}
    by_size = {}
    seen = 0
    started = time.time()
    for ident, size, cells, title in FORMATS[args.format](args.corpus, sizes):
        # The curated filter runs BEFORE the gate, not after: the gate is the
        # expensive part (exhaustive uniqueness, seconds per 15x15) and there is
        # nothing to learn from proving a puzzle that is not being imported.
        if (
            chosen is not None
            and (size, str(ident)) not in chosen
            and (None, str(ident)) not in chosen
        ):
            skipped_unchosen += 1
            continue
        if chosen is not None:
            found.add((size, str(ident)))
            found.add((None, str(ident)))
        # A corpus that TITLES its puzzles is titled here, verbatim, case and
        # all. A corpus that does not gets `<prefix><id>`, upper-cased because a
        # catalogue id has no case to preserve and the old bank's names were
        # uppercase. The two paths are separate rather than one path with an
        # .upper() on the end: `.upper()` over a real title ("Rise and Shine")
        # destroys a decision somebody made, and it did -- it used to sit on
        # this line and would have shipped 199 SHOUTED titles.
        if title and title in renames:
            renames_used.add(title)
            title = renames[title]
        name = title if title else ("%s%s" % (args.name_prefix, ident)).upper()
        # A corpus import is a long job and the gate's cost per puzzle varies by
        # orders of magnitude, so it says where it is rather than going quiet
        # for ten minutes. The per-puzzle timing is the useful half: a silent
        # run cannot tell "slow corpus" from "stuck on one pathological grid".
        before = time.time()
        ok, reason = gated(name, cells, args.gate_timeout)
        spent = time.time() - before
        seen += 1
        if ok is None:
            print("  SKIP  %-14s %2dx%-2d  %s" % (name, size, size, reason))
        elif spent > 5.0:
            print(
                "  SLOW  %-14s %2dx%-2d  %.0fs in the gate" % (name, size, size, spent)
            )
        if seen % 50 == 0:
            print(
                "  ... %d candidates, %d kept, %.0fs elapsed"
                % (seen, len(kept), time.time() - started)
            )
            sys.stdout.flush()
        reasons[reason] = reasons.get(reason, 0) + 1
        tally = by_size.setdefault(size, [0, 0])
        tally[1] += 1
        if not ok:
            continue
        tally[0] += 1
        record = authors.get(str(ident), authors.get(ident))
        author = author_of(record, args.author)
        source = format_source(args.source_template, ident)
        kept.append((name, size, cells, author, source))
        if args.limit and len(kept) >= args.limit:
            break

    # A rename that matched nothing did not happen, and the bank still carries
    # the title somebody meant to change. Nothing downstream can tell that from
    # a title that was never renamed, so it is a hard error here.
    if renames:
        unused = sorted(set(renames) - renames_used)
        if unused:
            sys.exit(
                "--rename lists %d title(s) that no puzzle in this corpus has: %s. A "
                "rename that matches nothing is a rename that silently did not happen."
                % (len(unused), ", ".join(repr(u) for u in unused))
            )

    # A record that was cited but never checked must not stamp the banner that
    # says "the permission is recorded in X": outside the repo the guard above
    # never runs, so the flag alone would assert a validation that did not
    # happen. Re-checked here so the two can never disagree.
    permitted = (
        bool(args.permission) and not free and check_permission(args.permission) is None
    )
    kept.sort(key=lambda entry: (entry[1], _natural(entry[0])))

    if unattributed:
        banner = UNATTRIBUTED_BANNER
    elif permitted:
        banner = PERMITTED_BANNER
    else:
        banner = BANNER
    # A committed file records the corpus's NAME; an evaluation file stays
    # outside the tree and its full path is the useful thing. An unattributed
    # import is committed, so it takes the basename too -- and here that matters
    # twice over: the path it was read from is a directory on Mario's Mac, and
    # writing one into a public repository would read as a source when the whole
    # point is that there is not one to give.
    named_by_file = permitted or bool(unattributed)

    with open(out, "w", encoding="utf-8") as handle:
        handle.write(
            banner
            % {
                "corpus": os.path.basename(args.corpus)
                if named_by_file
                else args.corpus,
                "license": args.license,
                "count": len(kept),
                "permission": args.permission or "(none)",
                "reason": unattributed or "(none given)",
            }
        )
        handle.write("\n@@license %s\n" % args.license)
        for name, _size, cells, author, source in kept:
            # An unattributed corpus writes no @author at all. Repeating
            # "@author unknown" 199 times is not a record of anything, and a
            # file full of the word makes the bank look half-credited rather
            # than deliberately uncredited -- which is the reading this whole
            # banner exists to prevent. The file-level @@license carries it.
            if not unattributed:
                handle.write("\n@author %s\n" % author)
                # Guarded HERE and not only by --source-template's refusal
                # upstream. Its twin above already was, and a pair where one
                # half defends itself and the other leans on a check two hundred
                # lines away is the fork's "bounding one of two input paths":
                # both are correct today and only one survives a refactor of the
                # flag validation.
                if source:
                    handle.write("@source %s\n" % source)
            else:
                handle.write("\n")
            handle.write("%s\n%s\n" % (name, render(cells)))

    print("read %s as %s" % (args.corpus, args.format))
    for reason, count in sorted(reasons.items(), key=lambda kv: -kv[1]):
        print("  %-46s %d" % (reason, count))
    print()
    for size in sorted(by_size):
        passed, total = by_size[size]
        share = (100.0 * passed / total) if total else 0.0
        print(
            "  %2dx%-2d  %3d/%-4d pass the gate (%.0f%%)"
            % (size, size, passed, total, share)
        )
    if chosen is not None:
        # A curated import must say which of the ids it was asked for never
        # turned up. An id that is missing from the corpus, is at a size this
        # run excluded, or fails the gate silently shrinks the bank, and a
        # count that only reports what was written cannot tell those apart from
        # a list that was simply shorter than it looked.
        absent = sorted(chosen - found, key=lambda e: _natural(e[1]))
        print()
        print(
            "  %d ids asked for, %d found in the corpus at their stated sizes, %d written"
            % (len(chosen), len(chosen) - len(absent), len(kept))
        )
        if absent:
            named = ["%s@%s" % (i, s if s else "any") for s, i in absent]
            print(
                "  %d asked-for ids were not in the corpus at that size: %s"
                % (
                    len(absent),
                    ", ".join(named[:20]) + (" ..." if len(absent) > 20 else ""),
                )
            )
        print("  %d corpus puzzles were skipped as not chosen" % skipped_unchosen)

    named = sum(1 for entry in kept if entry[3] != args.author)
    print()
    print("  %d puzzles written to %s" % (len(kept), out))
    print(
        "  %d of them name a known author; %d fall back to %r"
        % (named, len(kept) - named, args.author)
    )
    if unattributed:
        print()
        print("  UNATTRIBUTED. Nobody to credit, no licence to honour, no source to")
        print(
            "  cite, so none of the three was written. Reason recorded in the banner:"
        )
        print("  %s" % unattributed)
        print("  The bank is NOT public domain and NOT this fork's own work: a fork")
        print("  inherits CrossPlay's MIT code and does not inherit these puzzles.")
    elif not free and not args.permission:
        print()
        print(
            "  LICENCE %r is not redistributable. This file must not be" % args.license
        )
        print(
            "  committed, shipped, or published. Delete it when the evaluation is done."
        )
    elif not free:
        print()
        print(
            "  LICENCE %r is not redistributable; this import rests on the"
            % args.license
        )
        print("  permission recorded in %s." % args.permission)
        print("  That record travels with the data and must stay accurate. It is a")
        print(
            "  permission to THIS project, not a licence: a fork does not inherit it."
        )


if __name__ == "__main__":
    main()
