#!/usr/bin/env python3
"""Import a third-party nonogram corpus into pictures.txt format.

This exists because the pictures a person enjoys solving are DESIGNED, and
designing them is the one part of a nonogram nobody can automate: a generated
grid that happens to be unique and line-solvable is still, almost always, an
unreadable blob. So the interesting corpora are collections somebody drew and
somebody else played -- and every one of those is third-party work.

  python3 tools_local/picross/import_picross.py \\
      --corpus <file> --format janko-json --sizes 10,15 \\
      --author-map janko_authors.json \\
      --license 'all rights reserved' --source-template \\
        'https://www.janko.at/Raetsel/Nonogramme/{id}.a.htm' \\
      --out /tmp/janko.txt

WHAT THIS SCRIPT WILL NOT DO. It will not write a corpus into this repository
unless its licence is one of REDISTRIBUTABLE below. That is not a formality:
an imported puzzle whose licence is unstated is ALL RIGHTS RESERVED, and the
moment it lands in assets_local/ it is in a public repository, in every clone,
and in every release binary. Evaluating one locally is fine and is what this
script is for; shipping one is a permission somebody has to actually obtain.
The refusal is here rather than in a review checklist because a checklist is
not a mechanism.

THE GATE IS NOT REIMPLEMENTED HERE. `evaluate` is imported from gen_picross,
so an imported puzzle faces exactly the test a hand-drawn one faces: unique,
line-solvable, and filling its grid. A second copy of that gate would be a
second thing to keep in step, and the copy that drifts is always the one
nobody runs.

NAMES. Most corpora have no titles at all -- janko's certainly does not -- and
this writes `<prefix><id>` when there is nothing better. That is deliberate
and it is safe: the picross app shows a puzzle's name ONLY on the win screen,
after the picture is revealed (PicrossScreens::buildWin). The picker shows a
number and a size for an unsolved puzzle and the finished picture for a solved
one, so a name can neither spoil a reveal nor help a player choose. A catalogue
number is a poor punchline, though, which is a quality cost worth stating out
loud rather than a correctness one.
"""

import argparse
import json
import os
import re
import signal
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

from gen_picross import SIZES, evaluate  # noqa: E402  (path set above)

# Licences whose puzzles may be written into this repository. Anything else is
# evaluated locally and stays out of git. Spelled as the lowercase forms this
# script compares against, so "CC0-1.0" and "cc0-1.0" both pass.
REDISTRIBUTABLE = (
    "cc0-1.0",
    "cc-by-4.0",
    "cc-by-sa-4.0",
    "public domain",
    "mit",
)

BANNER = """# GENERATED by tools_local/picross/import_picross.py -- DO NOT COMMIT.
#
# These puzzles are THIRD-PARTY WORK under the licence recorded below. They are
# here to be evaluated locally: rendered, solved, judged. Redistributing them
# (committing this file, shipping a bank built from it, publishing a release
# that contains it) needs the author's permission first, which nobody has yet.
#
# Corpus:  %(corpus)s
# Licence: %(license)s
# Puzzles: %(count)d
"""


def parse_janko_json(path, sizes):
    """Yield (id, size, cells) from the puzzlekit Nonogram dataset.

    Keys look like '1051_10x10'; the number is the janko puzzle number, which
    is what its page URL and its author record are keyed by. `solution` is a
    'H W' line then rows of 'x' (solid) and '-' (empty), space separated.
    """
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    data = payload["data"] if isinstance(payload, dict) and "data" in payload else payload
    for key in sorted(data, key=_natural):
        shape = re.search(r"^(.+?)_(\d+)x(\d+)$", key)
        if not shape:
            continue
        ident, width, height = shape.group(1), int(shape.group(2)), int(shape.group(3))
        if width != height or width not in sizes:
            continue
        solution = data[key].get("solution")
        if not solution:
            continue
        rows = solution.strip().split("\n")[1:]  # drop the 'H W' header line
        cells = [[1 if token == "x" else 0 for token in row.split()] for row in rows]
        if len(cells) != height or any(len(row) != width for row in cells):
            continue
        yield ident, width, cells


def parse_non_dir(path, sizes):
    """Yield (id, size, cells) from a directory of .non files.

    The .non format stores CLUES rather than a solution, so a corpus in it
    cannot be imported without solving every puzzle first. Rather than grow a
    solver here, this reports what it found and asks for a solved corpus:
    guessing at a solution is exactly how a bank ends up with a puzzle whose
    picture nobody has ever seen.
    """
    del sizes
    count = sum(1 for entry in os.listdir(path) if entry.endswith(".non"))
    sys.exit(
        "%s holds %d .non files, which carry clues and no solution. Import a "
        "corpus that stores solved grids, or solve them first -- this script "
        "will not invent a picture from clues." % (path, count)
    )


FORMATS = {"janko-json": parse_janko_json, "non-dir": parse_non_dir}


# A permission record has to SAY these things before it counts. The check is
# deliberately about the shape of the record rather than its prose: it cannot
# tell whether a permission is real, only whether somebody wrote down who
# granted it, to whom, when, and that it is not a public licence. That last one
# is the load-bearing line -- a reader of a public repository will otherwise
# assume a fork inherits the right, and it does not.
PERMISSION_MUST_MENTION = (
    ("who granted it", ("granted by", "permission from", "permission was obtained")),
    ("that it is not a licence", ("not a licence", "not a license", "no public licence", "no public license")),
    ("that it does not travel to forks", ("does not extend", "does not transfer", "not inherited", "do not inherit")),
    ("a date", ("20",)),
)


def check_permission(ref):
    """None if `ref` cites a real, sufficiently specific permission record.

    Otherwise a sentence saying what is missing. The guard opens because a
    permission is RECORDED IN THE REPOSITORY, never because it was waived on the
    command line: the file has to exist and has to say the things a reader needs
    in order not to be misled. The next corpus faces the same check.
    """
    if not ref:
        return "No --permission given."
    path = ref if os.path.isabs(ref) else os.path.join(ROOT, ref)
    path = os.path.abspath(path)
    if not path.startswith(ROOT + os.sep):
        return "--permission must cite a file inside this repository, so the record ships with the data."
    if not os.path.exists(path):
        return "--permission cites %s, which does not exist." % ref
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read().lower()
    except OSError as exc:
        return "--permission cites %s, which could not be read (%s)." % (ref, exc)
    missing = [label for label, needles in PERMISSION_MUST_MENTION
               if not any(n in text for n in needles)]
    if missing:
        return ("%s does not record %s. A permission record has to state who granted it, "
                "that it is not a public licence, that it does not extend to forks, and when."
                % (ref, ", ".join(missing)))
    return None


class GateTimeout(Exception):
    pass


def gated(name, cells, seconds):
    """evaluate() with a wall-clock ceiling, or (None, why) when it runs over.

    The gate is NOT changed by this -- it is the same evaluate(), reaching the
    same verdict -- but a corpus is not a hand-drawn batch of twenty, and its
    cost per puzzle spans orders of magnitude. `count_solutions` is exhaustive,
    and a handful of grids in any large collection send it into the hundreds of
    seconds. Waiting is pointless: a puzzle that expensive to prove is one this
    bank can simply not take, and the alternative to a ceiling is an import that
    looks hung with nothing to read.

    Reported as its own outcome rather than folded into a failure, because
    "too slow to decide" and "decided against" are different facts.
    """
    if seconds <= 0:
        return evaluate(name, cells)

    def ring(_signum, _frame):
        raise GateTimeout()

    previous = signal.signal(signal.SIGALRM, ring)
    signal.setitimer(signal.ITIMER_REAL, seconds)
    try:
        return evaluate(name, cells)
    except GateTimeout:
        return None, "gate did not finish within %gs" % seconds
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, previous)


def _natural(key):
    """Sort '9_15x15' before '1051_10x10' rather than after it."""
    return [int(part) if part.isdigit() else part for part in re.split(r"(\d+)", key)]


def render(cells):
    return "\n".join("".join("#" if v else "." for v in row) for row in cells)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--corpus", required=True, help="corpus file or directory")
    ap.add_argument("--format", required=True, choices=sorted(FORMATS))
    ap.add_argument("--out", required=True, help="pictures.txt-format file to write")
    ap.add_argument(
        "--license",
        required=True,
        help="the corpus licence. Unstated means all rights reserved; say that.",
    )
    ap.add_argument("--author", default="unknown", help="fallback author")
    ap.add_argument(
        "--author-map",
        help="JSON {id: [author, source, ...]} overriding --author per puzzle",
    )
    ap.add_argument(
        "--source-template",
        default="",
        help="per-puzzle source URL, with {id} substituted",
    )
    ap.add_argument("--name-prefix", default="", help="name is <prefix><id>")
    ap.add_argument(
        "--sizes",
        default=",".join(str(s) for s in SIZES),
        help="comma-separated board sizes to keep",
    )
    ap.add_argument("--limit", type=int, default=0, help="stop after N passes")
    ap.add_argument(
        "--permission",
        default="",
        help="path (inside the repo) to the record of the permission that allows "
             "redistributing this corpus. Required to write a non-redistributable "
             "corpus into the tree; the record must name who granted it, say it is "
             "not a public licence, say it does not extend to forks, and be dated.",
    )
    ap.add_argument(
        "--gate-timeout",
        type=float,
        default=20.0,
        help="seconds to spend proving one puzzle before giving up on it (0 = forever)",
    )
    args = ap.parse_args()

    sizes = tuple(int(part) for part in args.sizes.split(",") if part.strip())
    unknown = [s for s in sizes if s not in SIZES]
    if unknown:
        sys.exit("sizes %r are not tiers the app has (%r)" % (unknown, list(SIZES)))

    out = os.path.abspath(args.out)
    inside_repo = out.startswith(ROOT + os.sep)
    free = args.license.strip().lower() in REDISTRIBUTABLE
    if inside_repo and not free:
        permission_error = check_permission(args.permission)
        if permission_error:
            sys.exit(
                "refusing to write %s inside this repository under licence %r.\n"
                "%s\n"
                "Third-party puzzles are all rights reserved until somebody obtains\n"
                "permission, and a file in the repo is a file in every clone and every\n"
                "release. Evaluate it outside the tree (a scratch directory) instead,\n"
                "or record the permission first and cite it with --permission."
                % (os.path.relpath(out, ROOT), args.license, permission_error)
            )

    authors = {}
    if args.author_map:
        with open(args.author_map, encoding="utf-8") as handle:
            authors = json.load(handle)

    kept = []
    reasons = {}
    by_size = {}
    seen = 0
    started = time.time()
    for ident, size, cells in FORMATS[args.format](args.corpus, sizes):
        name = "%s%s" % (args.name_prefix, ident)
        # A corpus import is a long job and the gate's cost per puzzle varies by
        # orders of magnitude, so it says where it is rather than going quiet
        # for ten minutes. The per-puzzle timing is the useful half: a silent
        # run cannot tell "slow corpus" from "stuck on one pathological grid".
        before = time.time()
        ok, reason = gated(name, cells, args.gate_timeout)
        spent = time.time() - before
        seen += 1
        if ok is None:
            print("  SKIP  %-14s %2dx%-2d  %s" % (name, size, size, reason))
        elif spent > 5.0:
            print("  SLOW  %-14s %2dx%-2d  %.0fs in the gate" % (name, size, size, spent))
        if seen % 50 == 0:
            print(
                "  ... %d candidates, %d kept, %.0fs elapsed"
                % (seen, len(kept), time.time() - started)
            )
            sys.stdout.flush()
        reasons[reason] = reasons.get(reason, 0) + 1
        tally = by_size.setdefault(size, [0, 0])
        tally[1] += 1
        if not ok:
            continue
        tally[0] += 1
        record = authors.get(str(ident)) or authors.get(ident) or []
        author = record[0] if record else args.author
        source = args.source_template.format(id=ident) if args.source_template else ""
        kept.append((name, size, cells, author, source))
        if args.limit and len(kept) >= args.limit:
            break

    kept.sort(key=lambda entry: (entry[1], _natural(entry[0])))

    with open(out, "w", encoding="utf-8") as handle:
        handle.write(
            BANNER
            % {
                "corpus": args.corpus,
                "license": args.license,
                "count": len(kept),
            }
        )
        handle.write("\n@@license %s\n" % args.license)
        for name, _size, cells, author, source in kept:
            handle.write("\n@author %s\n" % author)
            if source:
                handle.write("@source %s\n" % source)
            handle.write("%s\n%s\n" % (name.upper(), render(cells)))

    print("read %s as %s" % (args.corpus, args.format))
    for reason, count in sorted(reasons.items(), key=lambda kv: -kv[1]):
        print("  %-46s %d" % (reason, count))
    print()
    for size in sorted(by_size):
        passed, total = by_size[size]
        share = (100.0 * passed / total) if total else 0.0
        print("  %2dx%-2d  %3d/%-4d pass the gate (%.0f%%)" % (size, size, passed, total, share))
    named = sum(1 for entry in kept if entry[3] != args.author)
    print()
    print("  %d puzzles written to %s" % (len(kept), out))
    print("  %d of them name a known author; %d fall back to %r" % (named, len(kept) - named, args.author))
    if not free and not args.permission:
        print()
        print("  LICENCE %r is not redistributable. This file must not be" % args.license)
        print("  committed, shipped, or published. Delete it when the evaluation is done.")
    elif not free:
        print()
        print("  LICENCE %r is not redistributable; this import rests on the" % args.license)
        print("  permission recorded in %s." % args.permission)
        print("  That record travels with the data and must stay accurate. It is a")
        print("  permission to THIS project, not a licence: a fork does not inherit it.")


if __name__ == "__main__":
    main()
