#include "ToyBattleCore.h"

#include <cstring>

namespace toybattle {
namespace {

constexpr int other(int seat) { return seat ^ 1; }

uint32_t mix32(uint32_t x) {
  x += 0x9E3779B9u;
  x = (x ^ (x >> 16)) * 0x85EBCA6Bu;
  x = (x ^ (x >> 13)) * 0xC2B2AE35u;
  return x ^ (x >> 16);
}

// Counter-based rather than a stream: the i-th value of a seat's shuffle is a
// pure function of the seed, so a device can rebuild any part of it without
// having replayed the rest.
uint32_t shuffleBit(uint32_t seed, int seat, int i) {
  return mix32(seed ^ (static_cast<uint32_t>(seat) * 0x9E3779B9u) ^ (static_cast<uint32_t>(i) * 0x85EBCA6Bu));
}

uint8_t packTile(int seat, Troop kind) { return static_cast<uint8_t>((seat << 3) | static_cast<int>(kind)); }
constexpr int tileSeat(uint8_t packed) { return packed >> 3; }
constexpr Troop tileKind(uint8_t packed) { return static_cast<Troop>(packed & 0x07); }

bool hasEffect(Troop kind) { return kind != Troop::Kwak && kind != Troop::Roxy; }

// Gate and Nullify restrict the placement itself; the rest fire after it. Only
// the latter are something a player chooses to use or decline.
bool firesAfterPlacement(Special s) { return s != Special::None && s != Special::Gate && s != Special::Nullify; }

}  // namespace

// ---------------------------------------------------------------------------
// Terrain
// ---------------------------------------------------------------------------

namespace {

// 15 bases in a 5x3 lattice, an H.Q. at each end, and the eight cells of the
// lattice as regions. See the header for why this is ours and not Repos'.
constexpr Terrain buildProvingGround() {
  Terrain t{};
  t.name = "PROVING GROUND";
  t.baseCount = 15;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 7;

  // Rows of 5, left to right, top row first.
  for (int row = 0; row < 3; ++row) {
    for (int col = 0; col < 5; ++col) {
      const int b = row * 5 + col;
      t.x[b] = static_cast<uint16_t>(200 + col * 150);
      t.y[b] = static_cast<uint16_t>(200 + row * 300);
    }
  }
  t.x[15] = 60;
  t.y[15] = 500;  // seat 0's H.Q., left
  t.x[16] = 940;
  t.y[16] = 500;  // seat 1's H.Q., right

  int e = 0;
  for (int row = 0; row < 3; ++row) {
    for (int col = 0; col < 4; ++col) {
      t.edges[e++] = Edge{static_cast<uint8_t>(row * 5 + col), static_cast<uint8_t>(row * 5 + col + 1)};
    }
  }
  for (int row = 0; row < 2; ++row) {
    for (int col = 0; col < 5; ++col) {
      t.edges[e++] = Edge{static_cast<uint8_t>(row * 5 + col), static_cast<uint8_t>((row + 1) * 5 + col)};
    }
  }
  t.edges[e++] = Edge{15, 0};
  t.edges[e++] = Edge{15, 5};
  t.edges[e++] = Edge{15, 10};
  t.edges[e++] = Edge{16, 4};
  t.edges[e++] = Edge{16, 9};
  t.edges[e++] = Edge{16, 14};
  t.edgeCount = static_cast<uint8_t>(e);

  int r = 0;
  for (int row = 0; row < 2; ++row) {
    for (int col = 0; col < 4; ++col) {
      const int tl = row * 5 + col;
      t.regions[r].bases =
          (uint32_t{1} << tl) | (uint32_t{1} << (tl + 1)) | (uint32_t{1} << (tl + 5)) | (uint32_t{1} << (tl + 6));
      t.regions[r].medals = 2;
      ++r;
    }
  }
  t.regionCount = static_cast<uint8_t>(r);

  // Every special base kind, all on one board. No terrain Repos printed does
  // that -- each of theirs uses a single kind throughout -- but nothing in the
  // rules forbids it, and it gives the tests one place to exercise all seven.
  // Bases 4 and 9 carry the two placement restrictions because they are the
  // only two no other test places on.
  t.special[2] = static_cast<uint8_t>(Special::Recall);
  t.special[3] = static_cast<uint8_t>(Special::Exhume);
  t.special[7] = static_cast<uint8_t>(Special::Draw);
  t.special[8] = static_cast<uint8_t>(Special::Suppress);
  t.special[12] = static_cast<uint8_t>(Special::Shove);
  t.special[4] = static_cast<uint8_t>(Special::Nullify);
  t.special[9] = static_cast<uint8_t>(Special::Gate);
  // 6 and 7 only, the way Tropical Pool prints a pair of values on its buoys.
  t.gate[9] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Star)) | (1u << static_cast<int>(Troop::Roxy)));
  return t;
}

// CASTLE FIELD. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildCastleField() {
  Terrain t{};
  t.name = "CASTLE FIELD";
  t.baseCount = 15;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 7;

  const uint16_t xs[17] = {35, 965, 673, 327, 101, 500, 899, 673, 327, 35, 965, 0, 0, 1000, 1000, 500, 500};
  const uint16_t ys[17] = {7, 7, 182, 182, 500, 500, 500, 818, 818, 993, 993, 269, 731, 731, 269, 993, 7};
  for (int i = 0; i < 17; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 3},  {0, 16}, {1, 2}, {1, 16}, {2, 5},  {2, 6},  {2, 14}, {3, 4},  {3, 5}, {3, 11}, {4, 8},  {4, 11},
      {4, 12}, {5, 7},  {5, 8}, {6, 7},  {6, 13}, {6, 14}, {7, 10}, {7, 13}, {8, 9}, {8, 12}, {9, 15}, {10, 15},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 6) | (1u << 7) | (1u << 13), 1, 881, 674},
      {(1u << 4) | (1u << 8) | (1u << 12), 1, 119, 674},
      {(1u << 5) | (1u << 7) | (1u << 8) | (1u << 9) | (1u << 10), 3, 500, 834},
      {(1u << 0) | (1u << 1) | (1u << 2) | (1u << 3) | (1u << 5), 3, 500, 166},
      {(1u << 3) | (1u << 4) | (1u << 11), 1, 119, 326},
      {(1u << 2) | (1u << 6) | (1u << 14), 1, 881, 326},
      {(1u << 4) | (1u << 5), 2, 300, 500},
      {(1u << 5) | (1u << 6), 2, 700, 500},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[11] = static_cast<uint8_t>(Special::Recall);
  t.special[12] = static_cast<uint8_t>(Special::Recall);
  t.special[13] = static_cast<uint8_t>(Special::Recall);
  t.special[14] = static_cast<uint8_t>(Special::Recall);
  return t;
}

}  // namespace

// CITY OF CLOUDS. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildCityOfClouds() {
  Terrain t{};
  t.name = "CITY OF CLOUDS";
  t.baseCount = 14;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 8;

  const uint16_t xs[16] = {8, 992, 992, 8, 8, 992, 992, 8, 8, 992, 500, 500, 500, 500, 500, 500};
  const uint16_t ys[16] = {88, 88, 296, 296, 500, 500, 704, 704, 912, 912, 198, 398, 602, 802, 1000, 0};
  for (int i = 0; i < 16; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 3},  {0, 10}, {0, 15}, {1, 2},  {1, 10}, {1, 15}, {2, 5},  {2, 10}, {2, 11}, {3, 4},
      {3, 10}, {3, 11}, {4, 7},  {4, 11}, {4, 12}, {5, 6},  {5, 11}, {5, 12}, {6, 9},  {6, 12},
      {6, 13}, {7, 8},  {7, 12}, {7, 13}, {8, 13}, {8, 14}, {9, 13}, {9, 14},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 0) | (1u << 1) | (1u << 10), 1, 500, 98},
      {(1u << 1) | (1u << 2) | (1u << 10), 1, 907, 193},
      {(1u << 2) | (1u << 5) | (1u << 11), 1, 907, 398},
      {(1u << 5) | (1u << 6) | (1u << 12), 1, 907, 602},
      {(1u << 6) | (1u << 9) | (1u << 13), 1, 907, 807},
      {(1u << 7) | (1u << 8) | (1u << 13), 1, 93, 807},
      {(1u << 4) | (1u << 7) | (1u << 12), 1, 93, 602},
      {(1u << 3) | (1u << 4) | (1u << 11), 1, 93, 398},
      {(1u << 0) | (1u << 3) | (1u << 10), 1, 93, 193},
      {(1u << 2) | (1u << 3) | (1u << 10) | (1u << 11), 2, 500, 298},
      {(1u << 4) | (1u << 5) | (1u << 11) | (1u << 12), 2, 500, 500},
      {(1u << 6) | (1u << 7) | (1u << 12) | (1u << 13), 2, 500, 702},
      {(1u << 8) | (1u << 9) | (1u << 13), 1, 500, 902},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[10] = static_cast<uint8_t>(Special::Draw);
  t.special[11] = static_cast<uint8_t>(Special::Draw);
  t.special[12] = static_cast<uint8_t>(Special::Draw);
  t.special[13] = static_cast<uint8_t>(Special::Draw);
  return t;
}

// VOLCANIC JUNGLE. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildVolcanicJungle() {
  Terrain t{};
  t.name = "VOLCANIC JUNGLE";
  t.baseCount = 13;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 7;

  const uint16_t xs[15] = {12, 12, 12, 12, 500, 500, 500, 500, 988, 988, 988, 988, 500, 12, 988};
  const uint16_t ys[15] = {738, 500, 262, 6, 738, 6, 262, 500, 262, 500, 738, 994, 994, 994, 6};
  for (int i = 0; i < 15; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 1}, {0, 12}, {0, 13}, {1, 2}, {1, 7}, {2, 3}, {2, 6},  {3, 5},  {4, 7},   {4, 10},  {4, 12},
      {5, 6}, {5, 8},  {5, 14}, {6, 7}, {7, 9}, {8, 9}, {8, 14}, {9, 10}, {10, 11}, {11, 12}, {12, 13},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 5) | (1u << 6) | (1u << 7) | (1u << 8) | (1u << 9), 3, 744, 256},
      {(1u << 0) | (1u << 1) | (1u << 4) | (1u << 7) | (1u << 12), 3, 256, 744},
      {(1u << 4) | (1u << 7) | (1u << 9) | (1u << 10), 2, 744, 619},
      {(1u << 4) | (1u << 10) | (1u << 11) | (1u << 12), 2, 744, 866},
      {(1u << 1) | (1u << 2) | (1u << 6) | (1u << 7), 2, 256, 381},
      {(1u << 2) | (1u << 3) | (1u << 5) | (1u << 6), 2, 256, 134},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[2] = static_cast<uint8_t>(Special::Shove);
  t.special[10] = static_cast<uint8_t>(Special::Shove);
  return t;
}

// CURSED CEMETERY. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildCursedCemetery() {
  Terrain t{};
  t.name = "CURSED CEMETERY";
  t.baseCount = 15;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 7;

  const uint16_t xs[17] = {753, 440, 23, 977, 753, 247, 500, 4, 996, 753, 247, 23, 560, 977, 247, 41, 959};
  const uint16_t ys[17] = {997, 826, 826, 826, 672, 672, 500, 500, 500, 328, 328, 174, 174, 174, 3, 997, 3};
  for (int i = 0; i < 17; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 1},  {0, 3},   {0, 4},   {0, 15},  {1, 2},   {1, 5},   {1, 15},  {2, 5},   {3, 4},  {4, 5},
      {4, 6},  {4, 8},   {5, 6},   {5, 7},   {6, 9},   {6, 10},  {7, 10},  {8, 9},   {9, 10}, {9, 12},
      {9, 13}, {10, 11}, {10, 14}, {11, 14}, {12, 13}, {12, 14}, {12, 16}, {14, 16},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 10) | (1u << 11) | (1u << 14), 1, 164, 171},
      {(1u << 0) | (1u << 3) | (1u << 4), 1, 836, 829},
      {(1u << 9) | (1u << 12) | (1u << 13), 1, 758, 242},
      {(1u << 1) | (1u << 2) | (1u << 5), 1, 242, 758},
      {(1u << 4) | (1u << 5) | (1u << 6), 1, 500, 594},
      {(1u << 6) | (1u << 9) | (1u << 10), 1, 500, 406},
      {(1u << 9) | (1u << 10) | (1u << 12) | (1u << 14), 2, 371, 208},
      {(1u << 4) | (1u << 6) | (1u << 8) | (1u << 9), 2, 751, 500},
      {(1u << 5) | (1u << 6) | (1u << 7) | (1u << 10), 2, 249, 500},
      {(1u << 0) | (1u << 1) | (1u << 4) | (1u << 5), 2, 629, 792},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[2] = static_cast<uint8_t>(Special::Exhume);
  t.special[3] = static_cast<uint8_t>(Special::Exhume);
  t.special[11] = static_cast<uint8_t>(Special::Exhume);
  t.special[13] = static_cast<uint8_t>(Special::Exhume);
  return t;
}

// BATTLEFIELD. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildBattlefield() {
  Terrain t{};
  t.name = "BATTLEFIELD";
  t.baseCount = 14;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 8;

  const uint16_t xs[16] = {106, 894, 894, 500, 106, 0, 322, 678, 1000, 894, 500, 106, 106, 894, 500, 500};
  const uint16_t ys[16] = {998, 998, 795, 795, 795, 500, 500, 500, 500, 205, 205, 205, 2, 2, 998, 2};
  for (int i = 0; i < 16; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 4},  {0, 14}, {1, 2},  {1, 14}, {2, 3},  {2, 7}, {2, 8},  {3, 4},  {3, 6},   {3, 7},   {4, 5},   {4, 6},
      {5, 11}, {6, 10}, {6, 11}, {7, 9},  {7, 10}, {8, 9}, {9, 10}, {9, 13}, {10, 11}, {11, 12}, {12, 15}, {13, 15},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 9) | (1u << 10) | (1u << 11) | (1u << 12) | (1u << 13), 3, 500, 104},
      {(1u << 0) | (1u << 1) | (1u << 2) | (1u << 3) | (1u << 4), 3, 500, 896},
      {(1u << 2) | (1u << 7) | (1u << 8) | (1u << 9), 2, 852, 500},
      {(1u << 4) | (1u << 5) | (1u << 6) | (1u << 11), 2, 148, 500},
      {(1u << 6) | (1u << 10) | (1u << 11), 1, 313, 309},
      {(1u << 7) | (1u << 9) | (1u << 10), 1, 687, 309},
      {(1u << 2) | (1u << 3) | (1u << 7), 1, 687, 691},
      {(1u << 3) | (1u << 4) | (1u << 6), 1, 313, 691},
      {(1u << 3) | (1u << 6) | (1u << 7) | (1u << 10), 2, 500, 500},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[3] = static_cast<uint8_t>(Special::Suppress);
  t.special[5] = static_cast<uint8_t>(Special::Suppress);
  t.special[8] = static_cast<uint8_t>(Special::Suppress);
  t.special[10] = static_cast<uint8_t>(Special::Suppress);
  return t;
}

// CARIBBEAN SEA. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildCaribbeanSea() {
  Terrain t{};
  t.name = "CARIBBEAN SEA";
  t.baseCount = 12;
  t.hqCount = 3;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.hqSeat[2] = 0;
  t.medalsObjective = 5;

  const uint16_t xs[15] = {14, 482, 851, 995, 14, 14, 482, 995, 708, 358, 14, 482, 14, 482, 995};
  const uint16_t ys[15] = {13, 243, 121, 361, 243, 494, 494, 635, 785, 718, 718, 991, 991, 13, 991};
  for (int i = 0; i < 15; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 4}, {0, 13}, {1, 2}, {1, 4}, {1, 6},  {1, 13}, {2, 3},  {2, 8},  {3, 7},   {4, 5},
      {5, 6}, {5, 9},  {6, 8}, {7, 8}, {7, 14}, {8, 11}, {9, 10}, {9, 11}, {10, 12}, {11, 12},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 9) | (1u << 10) | (1u << 11), 1, 216, 854},
      {(1u << 5) | (1u << 6) | (1u << 8) | (1u << 9) | (1u << 11), 3, 524, 763},
      {(1u << 2) | (1u << 3) | (1u << 7) | (1u << 8), 2, 877, 560},
      {(1u << 1) | (1u << 2) | (1u << 6) | (1u << 8), 2, 640, 360},
      {(1u << 1) | (1u << 4) | (1u << 5) | (1u << 6), 2, 248, 368},
      {(1u << 0) | (1u << 1) | (1u << 4), 1, 248, 128},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }
  return t;
}

// TROPICAL POOL. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildTropicalPool() {
  Terrain t{};
  t.name = "TROPICAL POOL";
  t.baseCount = 13;
  t.hqCount = 4;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 0;
  t.hqSeat[2] = 1;
  t.hqSeat[3] = 1;
  t.medalsObjective = 6;

  const uint16_t xs[17] = {500, 500, 978, 978, 500, 22, 22, 22, 978, 978, 500, 22, 500, 22, 978, 22, 978};
  const uint16_t ys[17] = {3, 205, 205, 403, 500, 403, 205, 597, 597, 795, 795, 795, 997, 997, 997, 3, 3};
  for (int i = 0; i < 17; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 1}, {0, 2},  {0, 16}, {1, 2}, {1, 4},  {1, 6}, {1, 15}, {2, 3},   {3, 4},   {3, 8},   {4, 6},   {4, 7},
      {4, 9}, {4, 10}, {5, 6},  {5, 7}, {7, 11}, {8, 9}, {9, 10}, {10, 11}, {10, 12}, {10, 14}, {11, 12}, {12, 13},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 0) | (1u << 1) | (1u << 2), 1, 585, 125},
      {(1u << 10) | (1u << 11) | (1u << 12), 1, 415, 875},
      {(1u << 4) | (1u << 9) | (1u << 10), 1, 610, 691},
      {(1u << 1) | (1u << 4) | (1u << 6), 1, 390, 309},
      {(1u << 1) | (1u << 2) | (1u << 3) | (1u << 4), 2, 669, 334},
      {(1u << 4) | (1u << 7) | (1u << 10) | (1u << 11), 2, 363, 663},
      {(1u << 4) | (1u << 5) | (1u << 6) | (1u << 7), 2, 151, 438},
      {(1u << 3) | (1u << 4) | (1u << 8) | (1u << 9), 2, 849, 562},
  };
  t.gate[14] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Star)) |
                                    (1u << static_cast<int>(Troop::Roxy)));  // H.Q. 1
  t.gate[15] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Star)) |
                                    (1u << static_cast<int>(Troop::Roxy)));  // H.Q. 2
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[2] = static_cast<uint8_t>(Special::Gate);
  t.gate[2] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Skully)) |
                                   (1u << static_cast<int>(Troop::Capn)));
  t.special[4] = static_cast<uint8_t>(Special::Gate);
  t.gate[4] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Star)) |
                                   (1u << static_cast<int>(Troop::Roxy)));
  t.special[5] = static_cast<uint8_t>(Special::Gate);
  t.gate[5] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Jumbo)) |
                                   (1u << static_cast<int>(Troop::Hook)) | (1u << static_cast<int>(Troop::XB42)));
  t.special[8] = static_cast<uint8_t>(Special::Gate);
  t.gate[8] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Jumbo)) |
                                   (1u << static_cast<int>(Troop::Hook)) | (1u << static_cast<int>(Troop::XB42)));
  t.special[11] = static_cast<uint8_t>(Special::Gate);
  t.gate[11] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Skully)) |
                                    (1u << static_cast<int>(Troop::Capn)));
  return t;
}

// STATION METAL-X. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildStationMetalX() {
  Terrain t{};
  t.name = "STATION METAL-X";
  t.baseCount = 13;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 7;

  const uint16_t xs[15] = {12, 575, 988, 500, 12, 233, 500, 767, 500, 988, 12, 425, 988, 12, 988};
  const uint16_t ys[15] = {3, 105, 263, 328, 263, 500, 500, 500, 672, 737, 737, 895, 997, 997, 3};
  for (int i = 0; i < 15; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 3}, {0, 4},  {0, 14}, {1, 2},  {1, 3},  {1, 14},  {2, 3},   {2, 7},   {3, 4}, {3, 5},
      {3, 6}, {3, 7},  {4, 5},  {5, 6},  {5, 8},  {5, 10},  {6, 7},   {6, 8},   {7, 8}, {7, 9},
      {8, 9}, {8, 10}, {8, 11}, {8, 12}, {9, 12}, {10, 11}, {11, 13}, {12, 13},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 1) | (1u << 2) | (1u << 3), 1, 630, 221},   {(1u << 0) | (1u << 1) | (1u << 3), 1, 434, 130},
      {(1u << 0) | (1u << 3) | (1u << 4), 1, 109, 181},   {(1u << 3) | (1u << 4) | (1u << 5), 1, 248, 384},
      {(1u << 3) | (1u << 5) | (1u << 6), 1, 437, 440},   {(1u << 3) | (1u << 6) | (1u << 7), 1, 563, 440},
      {(1u << 2) | (1u << 3) | (1u << 7), 1, 752, 384},   {(1u << 6) | (1u << 7) | (1u << 8), 1, 563, 560},
      {(1u << 5) | (1u << 6) | (1u << 8), 1, 437, 560},   {(1u << 5) | (1u << 8) | (1u << 10), 1, 248, 616},
      {(1u << 8) | (1u << 10) | (1u << 11), 1, 370, 779}, {(1u << 8) | (1u << 9) | (1u << 12), 1, 891, 819},
      {(1u << 7) | (1u << 8) | (1u << 9), 1, 752, 616},   {(1u << 8) | (1u << 11) | (1u << 12), 1, 566, 870},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[5] = static_cast<uint8_t>(Special::Nullify);
  t.special[6] = static_cast<uint8_t>(Special::Nullify);
  t.special[7] = static_cast<uint8_t>(Special::Nullify);
  return t;
}

// LA CROISETTE. Traced in tools_local/terrain-editor and generated by its
// to_cpp.py -- do not hand-edit, retrace and regenerate instead.
//
// Topology is the printed board's. The coordinates are a starting layout
// for the panel, not a copy of the artwork.
constexpr Terrain buildLaCroisette() {
  Terrain t{};
  t.name = "LA CROISETTE";
  t.baseCount = 13;
  t.hqCount = 2;
  t.hqSeat[0] = 0;
  t.hqSeat[1] = 1;
  t.medalsObjective = 5;

  const uint16_t xs[15] = {680, 924, 462, 557, 998, 998, 557, 462, 924, 680, 18, 18, 18, 217, 257};
  const uint16_t ys[15] = {996, 818, 818, 605, 643, 357, 395, 182, 182, 4, 252, 500, 748, 996, 4};
  for (int i = 0; i < 15; ++i) {
    t.x[i] = xs[i];
    t.y[i] = ys[i];
  }

  const Edge edges[] = {
      {0, 1}, {0, 13}, {1, 2},  {2, 3}, {2, 4},  {2, 13}, {3, 4},  {3, 6},   {3, 11},  {4, 5},   {5, 6},
      {5, 7}, {6, 7},  {6, 11}, {7, 8}, {7, 14}, {8, 9},  {9, 14}, {10, 11}, {10, 14}, {11, 12}, {12, 13},
  };
  t.edgeCount = static_cast<uint8_t>(sizeof(edges) / sizeof(edges[0]));
  for (int i = 0; i < t.edgeCount; ++i) t.edges[i] = edges[i];

  struct R {
    uint32_t bases;
    uint8_t medals;
    uint16_t x;
    uint16_t y;
  };
  const R regions[] = {
      {(1u << 7) | (1u << 8) | (1u << 9), 1, 580, 93},
      {(1u << 5) | (1u << 6) | (1u << 7), 1, 607, 312},
      {(1u << 2) | (1u << 3) | (1u << 4), 1, 607, 688},
      {(1u << 0) | (1u << 1) | (1u << 2), 1, 570, 907},
      {(1u << 3) | (1u << 6) | (1u << 11), 1, 470, 500},
      {(1u << 6) | (1u << 7) | (1u << 10) | (1u << 11), 2, 265, 262},
      {(1u << 3) | (1u << 4) | (1u << 5) | (1u << 6), 2, 860, 500},
      {(1u << 2) | (1u << 3) | (1u << 11) | (1u << 12), 2, 251, 738},
  };
  t.regionCount = static_cast<uint8_t>(sizeof(regions) / sizeof(regions[0]));
  for (int i = 0; i < t.regionCount; ++i) {
    t.regions[i].bases = regions[i].bases;
    t.regions[i].medals = regions[i].medals;
    t.regions[i].x = regions[i].x;
    t.regions[i].y = regions[i].y;
  }

  t.special[1] = static_cast<uint8_t>(Special::Draw);
  t.special[4] = static_cast<uint8_t>(Special::Suppress);
  t.special[5] = static_cast<uint8_t>(Special::Suppress);
  t.special[8] = static_cast<uint8_t>(Special::Draw);
  t.special[10] = static_cast<uint8_t>(Special::Gate);
  t.gate[10] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Hook)) |
                                    (1u << static_cast<int>(Troop::XB42)) | (1u << static_cast<int>(Troop::Star)) |
                                    (1u << static_cast<int>(Troop::Roxy)));
  t.special[11] = static_cast<uint8_t>(Special::Nullify);
  t.special[12] = static_cast<uint8_t>(Special::Gate);
  t.gate[12] = static_cast<uint8_t>((1u << static_cast<int>(Troop::Kwak)) | (1u << static_cast<int>(Troop::Hook)) |
                                    (1u << static_cast<int>(Troop::XB42)) | (1u << static_cast<int>(Troop::Star)) |
                                    (1u << static_cast<int>(Troop::Roxy)));
  return t;
}

const Terrain kCastleField = withAdjacency(buildCastleField());
const Terrain kProvingGround = withAdjacency(buildProvingGround());
const Terrain kCityOfClouds = withAdjacency(buildCityOfClouds());
const Terrain kVolcanicJungle = withAdjacency(buildVolcanicJungle());
const Terrain kCursedCemetery = withAdjacency(buildCursedCemetery());
const Terrain kBattlefield = withAdjacency(buildBattlefield());
const Terrain kCaribbeanSea = withAdjacency(buildCaribbeanSea());
const Terrain kTropicalPool = withAdjacency(buildTropicalPool());
const Terrain kStationMetalX = withAdjacency(buildStationMetalX());
const Terrain kLaCroisette = withAdjacency(buildLaCroisette());

const Terrain& terrainAt(int index) {
  switch (static_cast<TerrainId>(index)) {
    case TerrainId::ProvingGround:
      return kProvingGround;
    case TerrainId::CityOfClouds:
      return kCityOfClouds;
    case TerrainId::VolcanicJungle:
      return kVolcanicJungle;
    case TerrainId::CursedCemetery:
      return kCursedCemetery;
    case TerrainId::Battlefield:
      return kBattlefield;
    case TerrainId::CaribbeanSea:
      return kCaribbeanSea;
    case TerrainId::TropicalPool:
      return kTropicalPool;
    case TerrainId::StationMetalX:
      return kStationMetalX;
    case TerrainId::LaCroisette:
      return kLaCroisette;
    case TerrainId::CastleField:
      break;
  }
  return kCastleField;
}

// ---------------------------------------------------------------------------
// Moves
// ---------------------------------------------------------------------------

Move Move::draw() {
  Move m;
  m.kind = Kind::Draw;
  m.stepCount = 0;
  return m;
}

Move Move::place(int slot, Troop kind, bool useEffect, int target) {
  Move m;
  m.kind = Kind::Place;
  m.stepCount = 1;
  m.steps[0].slot = static_cast<uint8_t>(slot);
  m.steps[0].kind = static_cast<uint8_t>(kind);
  m.steps[0].useEffect = useEffect;
  m.steps[0].target = static_cast<uint8_t>(target);
  return m;
}

Move& Move::then(int slot, Troop kind, bool useEffect, int target) {
  if (stepCount < kMaxChain) {
    steps[stepCount].slot = static_cast<uint8_t>(slot);
    steps[stepCount].kind = static_cast<uint8_t>(kind);
    steps[stepCount].useEffect = useEffect;
    steps[stepCount].target = static_cast<uint8_t>(target);
    ++stepCount;
  }
  return *this;
}

// ---------------------------------------------------------------------------
// Set-up
// ---------------------------------------------------------------------------

Troop Game::reserveAt(int seat, int index) const {
  uint8_t deck[kTroopsPerSeat];
  for (int i = 0; i < kTroopsPerSeat; ++i) deck[i] = static_cast<uint8_t>(i / kCopiesEach);
  for (int i = kTroopsPerSeat - 1; i > 0; --i) {
    const int j = static_cast<int>(shuffleBit(seed, seat, i) % static_cast<uint32_t>(i + 1));
    const uint8_t tmp = deck[i];
    deck[i] = deck[j];
    deck[j] = tmp;
  }
  return static_cast<Troop>(deck[index]);
}

void Game::newGame(uint32_t gameSeed, int terrainIndex, int starter, bool withSpecialBases) {
  *this = Game{};
  seed = gameSeed;
  terrain = static_cast<uint8_t>(terrainIndex);
  turn = static_cast<uint8_t>(starter);
  specialBases = withSpecialBases ? 1 : 0;

  // The starter racks 3 and the opponent 4: the second player's compensation
  // for moving second, and the only asymmetry in the set-up.
  const int opening[kSeats] = {starter == 0 ? 3 : 4, starter == 0 ? 4 : 3};
  for (int seat = 0; seat < kSeats; ++seat) {
    for (int i = 0; i < opening[seat]; ++i) {
      const Troop drawn = reserveAt(seat, kSetAside + reserveTaken[seat]);
      ++reserveTaken[seat];
      ++rack[seat][static_cast<int>(drawn)];
    }
  }
}

// ---------------------------------------------------------------------------
// Reading the board
// ---------------------------------------------------------------------------

int Game::rackSize(int seat) const {
  int n = 0;
  for (int k = 0; k < kTroopKinds; ++k) n += rack[seat][k];
  return n;
}

int Game::occupantSeat(int base) const {
  for (int i = placementCount - 1; i >= 0; --i) {
    if (placeSlot[i] == base) return tileSeat(placeTile[i]);
  }
  return kNoSeat;
}

Troop Game::occupantTroop(int base) const {
  for (int i = placementCount - 1; i >= 0; --i) {
    if (placeSlot[i] == base) return tileKind(placeTile[i]);
  }
  return Troop::Kwak;
}

int Game::stackDepth(int base) const {
  int n = 0;
  for (int i = 0; i < placementCount; ++i) {
    if (placeSlot[i] == base) ++n;
  }
  return n;
}

uint32_t Game::occupiedBy(int seat) const {
  // One forward pass, last write wins. Asking `occupantSeat` per base instead
  // would rescan the whole log for every base, and this runs inside move
  // generation.
  uint8_t top[kMaxBases];
  memset(top, kNoSeat, sizeof(top));
  for (int i = 0; i < placementCount; ++i) {
    if (placeSlot[i] < kMaxBases) top[placeSlot[i]] = static_cast<uint8_t>(tileSeat(placeTile[i]));
  }
  const Terrain& b = board();
  uint32_t mask = 0;
  for (int base = 0; base < b.baseCount; ++base) {
    if (top[base] == seat) mask |= uint32_t{1} << base;
  }
  return mask;
}

uint64_t Game::reachable(int seat) const {
  const Terrain& b = board();
  const uint32_t mine = occupiedBy(seat);

  uint64_t out = 0;
  for (int i = 0; i < b.hqCount; ++i) {
    if (b.hqSeat[i] == seat) out |= b.adj[b.baseCount + i];
  }
  // Grow through bases I hold. The H.Q. is the starting point only: it never
  // appears in `mine`, so it can never be walked through.
  for (bool grew = true; grew;) {
    grew = false;
    for (int base = 0; base < b.baseCount; ++base) {
      const uint64_t bit = uint64_t{1} << base;
      if (!(out & bit)) continue;
      if (!(mine & (uint32_t{1} << base))) continue;
      const uint64_t next = b.adj[base] & ~out;
      if (next) {
        out |= next;
        grew = true;
      }
    }
  }
  return out;
}

bool Game::canPlaceHere(int seat, int slot, Troop kind, bool hookWaiver) const {
  return placeableWith(seat, slot, kind, hookWaiver, reachable(seat));
}

// The same test with the reachable set hoisted out. Move generation asks this
// 8 kinds x 17 slots times per position, and recomputing connectivity inside
// that loop is a two-orders-of-magnitude mistake in the brain's inner loop.
bool Game::placeableWith(int seat, int slot, Troop kind, bool hookWaiver, uint64_t reach) const {
  const Terrain& b = board();
  if (slot < 0 || slot >= b.slotCount()) return false;
  if (rack[seat][static_cast<int>(kind)] == 0) return false;
  // A suppressed troop is lying facedown on the rack. It still counts against
  // the 8, it just cannot be played this turn.
  if (frozenKind[seat] == static_cast<uint8_t>(kind)) return false;

  // Both placement restrictions are special base rules, so both switch off with
  // the setting: "treat all special bases like bases with no effect."
  if (specialBases) {
    const uint8_t admits = b.gate[slot];
    if (admits != 0 && !(admits & (1u << static_cast<int>(kind)))) return false;
  }

  const bool connected = (reach & (uint64_t{1} << slot)) != 0;

  if (b.isHq(slot)) {
    // Never your own, and Hook's waiver does not reach here: the aid is
    // explicit that the H.Q. is not a base.
    if (b.hqOwner(slot) == seat) return false;
    return connected;
  }

  const int holder = occupantSeat(slot);
  if (holder != kNoSeat && holder != seat && !covers(kind, occupantTroop(slot))) return false;

  if (connected) return true;
  // Hook is not barred from a base that nullifies effects -- its waiver just
  // does not work there, so it has to trace back to the H.Q. like anything
  // else. That is why this sits BELOW the connected check and not above it:
  // above, it would refuse the placement outright, which is the strict reading
  // Mario ruled against on 2026-08-11. `testGateAndNullify` pins both halves.
  if (specialBases && b.specialAt(slot) == Special::Nullify) return false;
  return hookWaiver && kind == Troop::Hook;
}

bool Game::canDraw(int seat) const { return rackSize(seat) < kRackLimit && reserveRemaining(seat) > 0; }

int Game::legalPlacements(int seat, Step* out, int max) const {
  const Terrain& b = board();
  const uint64_t reach = reachable(seat);
  int n = 0;
  for (int k = 0; k < kTroopKinds && n < max; ++k) {
    if (rack[seat][k] == 0) continue;
    const Troop kind = static_cast<Troop>(k);
    for (int slot = 0; slot < b.slotCount() && n < max; ++slot) {
      if (!placeableWith(seat, slot, kind, /*hookWaiver=*/true, reach)) continue;
      Step s;
      s.slot = static_cast<uint8_t>(slot);
      s.kind = static_cast<uint8_t>(k);
      // Minimally committed: the effect is declined except where the
      // placement itself only stands up because of Hook's waiver. Choosing
      // effects, and Jumbo's target, is the caller's business.
      s.useEffect = !placeableWith(seat, slot, kind, /*hookWaiver=*/false, reach);
      out[n++] = s;
    }
  }
  return n;
}

bool Game::hasAnyLegalMove(int seat) const {
  if (canDraw(seat)) return true;
  Step scratch[1];
  return legalPlacements(seat, scratch, 1) > 0;
}

bool Game::isWellFormed() const {
  if (terrain >= kTerrainCount) return false;
  const Terrain& b = board();

  if (turn >= kSeats) return false;
  if (phase > static_cast<uint8_t>(Phase::GameOver)) return false;
  if (ending > static_cast<uint8_t>(Ending::Stuck)) return false;
  if (winner != kNoSeat && winner >= kSeats) return false;
  if (specialBases > 1) return false;
  if (placementCount > kMaxPlacements) return false;

  for (int i = 0; i < placementCount; ++i) {
    if (placeSlot[i] >= b.slotCount()) return false;
    if (tileSeat(placeTile[i]) >= kSeats) return false;
  }

  if (b.regionCount < kMaxRegions && (regionsTaken >> b.regionCount) != 0) return false;
  int banked = 0;
  for (int r = 0; r < b.regionCount; ++r) {
    if (regionsTaken & (1u << r)) banked += b.regions[r].medals;
  }
  if (medals[0] + medals[1] != banked) return false;

  for (int seat = 0; seat < kSeats; ++seat) {
    if (reserveTaken[seat] > kReserveSize) return false;
    if (rackSize(seat) > kRackLimit) return false;
    if (frozenKind[seat] != kNoSlot && frozenKind[seat] >= kTroopKinds) return false;
    if (frozenKind[seat] != kNoSlot && rack[seat][frozenKind[seat]] == 0) return false;

    // Per-kind conservation against the shuffle the seed describes. Anything
    // drawn is on the rack, in the discard, or on the board -- and this also
    // proves the seed and the state belong to the same game, which a length
    // check on the packet cannot.
    int drawn[kTroopKinds] = {};
    for (int i = 0; i < reserveTaken[seat]; ++i) ++drawn[static_cast<int>(reserveAt(seat, kSetAside + i))];
    int held[kTroopKinds] = {};
    for (int k = 0; k < kTroopKinds; ++k) held[k] = rack[seat][k] + discarded[seat][k];
    for (int i = 0; i < placementCount; ++i) {
      if (tileSeat(placeTile[i]) == seat) ++held[static_cast<int>(tileKind(placeTile[i]))];
    }
    for (int k = 0; k < kTroopKinds; ++k) {
      if (held[k] != drawn[k]) return false;
      if (rack[seat][k] + discarded[seat][k] > kCopiesEach) return false;
    }
  }
  return true;
}

// ---------------------------------------------------------------------------
// Applying a move
// ---------------------------------------------------------------------------

namespace {

void drawTroops(Game& g, int seat, int wanted) {
  const int space = kRackLimit - g.rackSize(seat);
  int n = wanted < space ? wanted : space;
  if (n > g.reserveRemaining(seat)) n = g.reserveRemaining(seat);
  for (int i = 0; i < n; ++i) {
    const Troop drawn = g.reserveAt(seat, kSetAside + g.reserveTaken[seat]);
    ++g.reserveTaken[seat];
    ++g.rack[seat][static_cast<int>(drawn)];
  }
}

// Pops the visible troop off a base. Every removal in this game is of a
// visible troop, so this is the only shape a removal ever takes.
bool popVisible(Game& g, int base, int* outSeat, Troop* outKind) {
  for (int i = g.placementCount - 1; i >= 0; --i) {
    if (g.placeSlot[i] != base) continue;
    *outSeat = tileSeat(g.placeTile[i]);
    *outKind = tileKind(g.placeTile[i]);
    const int tail = g.placementCount - i - 1;
    if (tail > 0) {
      memmove(&g.placeSlot[i], &g.placeSlot[i + 1], static_cast<size_t>(tail));
      memmove(&g.placeTile[i], &g.placeTile[i + 1], static_cast<size_t>(tail));
    }
    --g.placementCount;
    return true;
  }
  return false;
}

void endGame(Game& g, int winnerSeat, Ending why) {
  g.phase = static_cast<uint8_t>(Phase::GameOver);
  g.winner = static_cast<uint8_t>(winnerSeat);
  g.ending = static_cast<uint8_t>(why);
}

// Regions fall the instant their last base is held, for either seat, after any
// change to the board -- including one that merely uncovers a buried tile.
void settleRegions(Game& g) {
  const Terrain& b = g.board();
  for (int seat = 0; seat < kSeats; ++seat) {
    const uint32_t mine = g.occupiedBy(seat);
    for (int r = 0; r < b.regionCount; ++r) {
      const uint16_t bit = static_cast<uint16_t>(1u << r);
      if (g.regionsTaken & bit) continue;
      if ((mine & b.regions[r].bases) != b.regions[r].bases) continue;
      g.regionsTaken = static_cast<uint16_t>(g.regionsTaken | bit);
      g.medals[seat] = static_cast<uint8_t>(g.medals[seat] + b.regions[r].medals);
      if (g.medals[seat] >= b.medalsObjective && g.currentPhase() == Phase::Playing) {
        endGame(g, seat, Ending::MedalsObjective);
      }
    }
  }
}

// Picks a troop from a rack at random, the way "point at one without looking"
// picks one. Returns kTroopKinds when the rack is empty.
int blindPick(Game& g, int seat, uint32_t salt) {
  const int held = g.rackSize(seat);
  if (held == 0) return kTroopKinds;
  int pick =
      static_cast<int>(mix32(g.seed ^ salt ^ (static_cast<uint32_t>(g.rngTick) << 16)) % static_cast<uint32_t>(held));
  ++g.rngTick;
  for (int k = 0; k < kTroopKinds; ++k) {
    if (pick < g.rack[seat][k]) return k;
    pick -= g.rack[seat][k];
  }
  return kTroopKinds;
}

// The special base under a placement, applied after every troop effect of the
// turn. Two rules govern all of them: only visible troops can be interacted
// with, and an effect that would push a rack past 8 cannot be applied at all
// (the aid is explicit that it is refused rather than clamped).
//
// `placed` is the slot whose base is firing, so Recall can exclude the troop
// that just landed there.
bool applyBaseEffect(Game& g, int seat, const Step& s, int placed) {
  const Terrain& b = g.board();
  const Special what = b.specialAt(placed);
  const int foe = other(seat);

  switch (what) {
    case Special::None:
    case Special::Gate:
    case Special::Nullify:
      return false;  // restrictions, not effects: nothing fires afterwards

    case Special::Draw:
      if (g.rackSize(seat) >= kRackLimit) return false;
      if (g.reserveRemaining(seat) == 0) return false;
      drawTroops(g, seat, 1);
      return true;

    case Special::Exhume: {
      if (g.rackSize(seat) >= kRackLimit) return false;
      if (s.baseKind >= kTroopKinds) return false;
      if (g.discarded[seat][s.baseKind] == 0) return false;
      --g.discarded[seat][s.baseKind];
      ++g.rack[seat][s.baseKind];
      return true;
    }

    case Special::Recall: {
      if (g.rackSize(seat) >= kRackLimit) return false;
      if (s.baseFrom >= b.baseCount) return false;
      if (s.baseFrom == placed) return false;  // "one of your OTHER troops"
      if (g.occupantSeat(s.baseFrom) != seat) return false;
      int who = 0;
      Troop what2 = Troop::Kwak;
      if (!popVisible(g, s.baseFrom, &who, &what2)) return false;
      ++g.rack[seat][static_cast<int>(what2)];
      settleRegions(g);
      return true;
    }

    case Special::Shove: {
      // An adjacent enemy troop, moved to a base beside where it stood,
      // ignoring the placement rules entirely -- so strength, ownership and
      // connection all stop mattering for this one move.
      if (s.baseFrom >= b.baseCount || s.baseTo >= b.baseCount) return false;
      if (!(b.adj[placed] & (uint64_t{1} << s.baseFrom))) return false;
      if (!(b.adj[s.baseFrom] & (uint64_t{1} << s.baseTo))) return false;
      if (g.occupantSeat(s.baseFrom) != foe) return false;
      int who = 0;
      Troop what2 = Troop::Kwak;
      if (!popVisible(g, s.baseFrom, &who, &what2)) return false;
      g.placeSlot[g.placementCount] = s.baseTo;
      g.placeTile[g.placementCount] = packTile(who, what2);
      ++g.placementCount;
      settleRegions(g);
      return true;
    }

    case Special::Suppress: {
      const int picked = blindPick(g, foe, 0xB1F1E1D0u);
      if (picked >= kTroopKinds) return false;
      g.frozenKind[foe] = static_cast<uint8_t>(picked);
      return true;
    }
  }
  return false;
}

bool applyStep(Game& g, int seat, const Step& s, bool chainContinues) {
  const Terrain& b = g.board();
  const Troop kind = static_cast<Troop>(s.kind);
  if (s.kind >= kTroopKinds) return false;

  // Troop effects do not happen on a Station Metal-X base, so claiming one
  // there is not a legal move rather than a silent no-op.
  if (g.specialBases && b.specialAt(s.slot) == Special::Nullify && s.useEffect) return false;
  // And the base flag has to name a base that actually has something to fire.
  if (s.useBase && !(g.specialBases && firesAfterPlacement(b.specialAt(s.slot)))) return false;

  // A Cap'n's effect *is* the extra placement, so the flag and the presence of
  // a following step have to agree. Anything else is a move that means two
  // things at once.
  if (chainContinues && !(kind == Troop::Capn && s.useEffect)) return false;
  if (!chainContinues && kind == Troop::Capn && s.useEffect) return false;
  if (s.useEffect && !hasEffect(kind)) return false;

  const bool waiver = s.useEffect && kind == Troop::Hook;
  if (!g.canPlaceHere(seat, s.slot, kind, waiver)) return false;

  --g.rack[seat][s.kind];
  g.placeSlot[g.placementCount] = s.slot;
  g.placeTile[g.placementCount] = packTile(seat, kind);
  ++g.placementCount;

  if (b.isHq(s.slot)) {
    endGame(g, seat, Ending::HqCaptured);
    return true;
  }

  settleRegions(g);
  if (g.currentPhase() != Phase::Playing) return true;

  if (!s.useEffect) return true;

  switch (kind) {
    case Troop::Skully:
      drawTroops(g, seat, 2);
      break;
    case Troop::Star:
      drawTroops(g, seat, 1);
      break;
    case Troop::Hook:
      break;  // the waiver was the effect, and it was spent on the placement
    case Troop::Capn:
      break;  // the extra placement is the next step
    case Troop::Jumbo: {
      // One section of path, and only a visible enemy troop.
      if (s.target == kNoSlot) return false;
      if (s.target >= b.baseCount) return false;
      if (!(b.adj[s.slot] & (uint64_t{1} << s.target))) return false;
      if (g.occupantSeat(s.target) != other(seat)) return false;
      int victimSeat = 0;
      Troop victimKind = Troop::Kwak;
      if (!popVisible(g, s.target, &victimSeat, &victimKind)) return false;
      ++g.discarded[victimSeat][static_cast<int>(victimKind)];
      settleRegions(g);
      break;
    }
    case Troop::XB42: {
      const int foe = other(seat);
      const int picked = blindPick(g, foe, 0xB5000000u);
      if (picked < kTroopKinds) {
        --g.rack[foe][picked];
        ++g.discarded[foe][picked];
        // A suppressed troop that has just been shot off the rack cannot stay
        // suppressed: the mark would otherwise freeze a kind the seat is free
        // to draw again later.
        if (g.frozenKind[foe] == static_cast<uint8_t>(picked) && g.rack[foe][picked] == 0) {
          g.frozenKind[foe] = kNoSlot;
        }
      }
      break;
    }
    case Troop::Kwak:
    case Troop::Roxy:
      break;  // rejected above; no effect to apply
  }
  return true;
}

bool tryApply(Game& g, const Move& move) {
  if (g.currentPhase() != Phase::Playing) return false;
  const int seat = g.turn;

  if (move.kind == Move::Kind::Draw) {
    if (move.stepCount != 0) return false;
    if (!g.canDraw(seat)) return false;
    drawTroops(g, seat, 2);
  } else {
    if (move.stepCount < 1 || move.stepCount > kMaxChain) return false;
    for (int i = 0; i < move.stepCount; ++i) {
      const bool chainContinues = i + 1 < move.stepCount;
      if (!applyStep(g, seat, move.steps[i], chainContinues)) return false;
      // A win mid-chain ends the game there: the rest of the Cap'n's chain
      // never happens.
      if (g.currentPhase() != Phase::Playing) return true;
    }

    // "First apply all the effects of Troops you just placed, then apply any
    // special base effects." So a Cap'n chain runs both troop effects before
    // either base fires, and the bases then fire in the order they were
    // occupied. Getting this backwards is a real difference: a base that
    // returns a troop to your rack changes what the extra placement could
    // have been.
    for (int i = 0; i < move.stepCount; ++i) {
      const Step& s = move.steps[i];
      if (!s.useBase) continue;
      if (!applyBaseEffect(g, seat, s, s.slot)) return false;
      if (g.currentPhase() != Phase::Playing) return true;
    }
  }

  // The suppressed troop goes back on the rack at the end of the turn it sat
  // out. Clearing the mover's own mark here is exactly that: the enemy set it
  // during their turn, this turn happened without it, and now it is spent.
  g.frozenKind[seat] = kNoSlot;

  g.turn = static_cast<uint8_t>(other(seat));
  if (!g.hasAnyLegalMove(g.turn)) {
    const int stuck = g.turn;
    const int foe = other(stuck);
    // Most medals, and a tie goes against whoever could not act.
    const int winnerSeat = g.medals[stuck] > g.medals[foe] ? stuck : foe;
    endGame(g, winnerSeat, Ending::Stuck);
  }
  return true;
}

}  // namespace

bool Game::isLegal(const Move& move) const {
  Game trial = *this;
  return tryApply(trial, move);
}

bool Game::apply(const Move& move) {
  Game trial = *this;
  if (!tryApply(trial, move)) return false;
  *this = trial;
  return true;
}

}  // namespace toybattle
