#!/bin/bash
# Regenerate the generated font cuts in src/apps_local/ui/fonts/.
#
#   ./tools_local/toybox/gen_toybox_fonts.sh [size ...]     # default: the cuts we ship
#
# The output is committed, because regenerating needs the TTF and two Python
# packages, and a checkout should build without either. Edit the size list, run
# this, commit the headers.
#
# Jersey 25 is SIL OFL (github.com/scfried/soft-type-jersey, via Google Fonts).
# It is fetched rather than vendored because lib/EpdFont/fontsrc/ is gitignored
# upstream and the original conversion used a file in /tmp that is long gone --
# which is exactly why this script exists rather than a note in a header.
#
# Two details that matter, both learned by diffing a regenerated cut against the
# committed one:
#
#   * Subset first. Converting the whole font produces a 16KB table instead of
#     a 4KB one, because fontconvert exports every glyph it finds.
#   * 1-bit, never --2bit. GfxRenderer's BW path paints a pixel for ANY coverage
#     above zero, so an antialiased cut floods to solid black and turns to mush.
#     See docs/design-language.md.
#
# RUNNING THIS SCRIPT TODAY CHANGES GLYPH METRICS. Measured 2026-08-30 against
# the committed headers, by hashing the glyph data rather than the header text:
#
#   toybox_14  regenerates BYTE-IDENTICAL
#   toybox_20  4159 -> 4377 data bytes, and metrics move
#   toybox_30  9191 -> 9397 data bytes, and metrics move
#
# Not a packing difference. Every glyph gets a pixel taller: in toybox_20 the
# "!" descriptor goes from {6,25,146,2,25,19,0} to {6,26,146,2,26,20,0}. The
# fork's centring constants in ToyboxTokens.h are derived from exactly those ink
# heights, and inkCentred() solves against them, so a regeneration silently
# shifts text position in every app that uses these cuts. The current freetype
# or fonttools is not the one that produced the committed headers, and nothing
# pins it.
#
# So: do not regenerate 20 or 30 to add glyphs until that is resolved, either by
# pinning the toolchain that made the committed cuts or by accepting the new
# metrics and auditing every screen against the new ToyboxTokens values.
#
# THERE IS CURRENTLY NO REASON TO REGENERATE ANYTHING. The only thing that
# wanted a wider subset was seven accented capitals for a Spanish deck, and that
# was dropped on 2026-08-30. Nothing in the fork needs a glyph the committed
# cuts do not already carry, so the trap above stays unexploded as long as
# nobody regenerates for its own sake.
#
# CUT 10 IS NOT REGENERATED BY THIS SCRIPT AND THE GUARD BELOW REFUSES IT. The
# committed toybox_10.h carries a far wider set than anything here produces:
# Latin-1, Latin Extended-A, combining diacritics, curly quotes, the euro and
# U+2026. Regenerating it from this script would silently drop 31KB of glyphs
# that no test asserts the presence of. See the toybox-10-is-not-reproducible
# note before touching it.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"

SIZES=("$@")
[ ${#SIZES[@]} -eq 0 ] && SIZES=(14 20 30)

for size in "${SIZES[@]}"; do
  if [ "$size" = "10" ]; then
    echo "refusing to regenerate toybox_10: the committed header carries Latin-1," >&2
    echo "Latin Extended-A, combining marks and U+2026, none of which this script" >&2
    echo "produces. Regenerating would drop ~31KB of glyphs silently." >&2
    exit 1
  fi
done

SRCDIR=lib/EpdFont/builtinFonts/source
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

curl -fsSL "https://github.com/google/fonts/raw/main/ofl/jersey25/Jersey25-Regular.ttf" -o "$WORK/jersey25.ttf"
uv run --quiet --with fonttools pyftsubset "$WORK/jersey25.ttf" \
  --unicodes="U+0020-007E" --output-file="$WORK/jersey25-subset.ttf"

# The reading face is a different family and a different argument. Noto Serif,
# because it is what the EPUB reader sets books in, converted at 1 bit HERE
# rather than taken from lib/EpdFont/builtinFonts/ -- those cuts are --2bit and
# flood to mush through the BW glyph path. --force-autohint keeps stem widths
# even at 14px, which is what stops a 1-bit serif going ragged.
#
# Latin-1 as well as ASCII: Hacker News prose is full of accented names, and a
# codepoint with no glyph draws as nothing at all.
if [ ${#SIZES[@]} -eq 3 ]; then
  SERIF="$SRCDIR/NotoSerif/NotoSerif-Regular.ttf"
  uv run --quiet --with fonttools pyftsubset "$SERIF" \
    --unicodes="U+0020-007E,U+00A0-00FF" --output-file="$WORK/notoserif-subset.ttf"
  out="src/apps_local/ui/fonts/reading_serif_14.h"
  uv run --quiet --with freetype-py --with fonttools \
    python lib/EpdFont/scripts/fontconvert.py reading_serif_14 14 "$WORK/notoserif-subset.ttf" \
    --force-autohint 2>/dev/null | grep -v "extracted$" > "$out"
  sed -i '' -e "s| \* Command used: .*| * Command used: tools_local/toybox/gen_toybox_fonts.sh (fontconvert.py reading_serif_14 14 NotoSerif-Regular subset, --force-autohint)|" "$out"
  echo "wrote $out"
fi

for size in "${SIZES[@]}"; do
  out="src/apps_local/ui/fonts/toybox_${size}.h"
  uv run --quiet --with freetype-py --with fonttools \
    python lib/EpdFont/scripts/fontconvert.py "toybox_${size}" "${size}" "$WORK/jersey25-subset.ttf" \
    2>/dev/null | grep -v "extracted$" > "$out"
  # fontconvert records the absolute path it was handed; keep it reproducible.
  sed -i '' -e "s| \* Command used: .*| * Command used: tools_local/toybox/gen_toybox_fonts.sh (fontconvert.py toybox_${size} ${size} jersey25-subset.ttf)|" "$out"
  echo "wrote $out"
done
