-- The board: one card per piece of work, its blockers, who owns what, and
-- Mario's inbox as a view. Written by the `board` CLI with the service key,
-- by the site's report function with the service key, and read by Mario's
-- inbox page as an authenticated user. Nobody else has any access: RLS is on
-- everywhere and the only policy admits the emails in allowed_users.

create table if not exists cards (
  id bigint generated by default as identity primary key,
  title text not null,
  app text not null default 'general',
  kind text not null default 'task' check (kind in ('bug', 'feature', 'task')),
  body text not null default '',
  state text not null default 'reported'
    check (state in ('reported', 'triaged', 'working', 'review', 'merged', 'released', 'done', 'parked')),
  source text not null default 'session' check (source in ('session', 'site', 'import')),
  tree text,
  branch text,
  session text,
  device text,
  version text,
  reporter_email text,
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists blockers (
  id bigint generated by default as identity primary key,
  card_id bigint not null references cards (id) on delete cascade,
  n integer not null,
  need text not null check (need in ('desk', 'design', 'info', 'mario', 'device', 'other')),
  ask text not null,
  "default" text not null default '',
  open boolean not null default true,
  by_session text,
  answer_choice text,
  answer_note text,
  answered_at timestamptz,
  created_at timestamptz not null default now(),
  unique (card_id, n)
);

create table if not exists history (
  id bigint generated by default as identity primary key,
  card_id bigint not null references cards (id) on delete cascade,
  at timestamptz not null default now(),
  what text not null
);

create table if not exists owners (
  app text primary key,
  session text,
  tree text,
  since timestamptz not null default now()
);

create table if not exists claims (
  name text primary key check (name in ('orchestrator', 'integrator')),
  session text not null,
  display_name text,
  since timestamptz not null default now()
);

create table if not exists sessions (
  id text primary key,
  cwd text,
  card_id bigint references cards (id) on delete set null,
  started_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

-- Who may read and write from a browser. The CLI and the site function use
-- the service key and bypass this; the inbox page signs in by magic link and
-- must be one of these.
create table if not exists allowed_users (
  email text primary key
);
insert into allowed_users (email) values ('marioalejandroruizsarmiento@gmail.com')
  on conflict do nothing;

create or replace function is_allowed() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from allowed_users
    where email = coalesce(auth.jwt() ->> 'email', '')
  )
$$;

create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end
$$;
drop trigger if exists cards_touch on cards;
create trigger cards_touch before update on cards
  for each row execute function touch_updated_at();

-- Mario's inbox: every open blocker that needs him, with its card.
create or replace view inbox as
  select b.id as blocker_id, b.n, c.id as card_id, c.title, c.app, c.kind, c.body,
         c.state, b.ask, b."default", b.created_at
  from blockers b join cards c on c.id = b.card_id
  where b.open and b.need = 'mario'
  order by b.created_at;

alter table cards enable row level security;
alter table blockers enable row level security;
alter table history enable row level security;
alter table owners enable row level security;
alter table claims enable row level security;
alter table sessions enable row level security;
alter table allowed_users enable row level security;

do $$
declare t text;
begin
  foreach t in array array['cards', 'blockers', 'history', 'owners', 'claims', 'sessions'] loop
    execute format('drop policy if exists allowed_all on %I', t);
    execute format(
      'create policy allowed_all on %I for all to authenticated using (is_allowed()) with check (is_allowed())', t);
  end loop;
end $$;

drop policy if exists allowed_read_self on allowed_users;
create policy allowed_read_self on allowed_users for select to authenticated
  using (email = coalesce(auth.jwt() ->> 'email', ''));

-- Photos from the report form. Private bucket; the function uploads with the
-- service key, the inbox page reads as an allowed user.
insert into storage.buckets (id, name, public)
  values ('photos', 'photos', false)
  on conflict (id) do nothing;
drop policy if exists photos_allowed_read on storage.objects;
create policy photos_allowed_read on storage.objects for select to authenticated
  using (bucket_id = 'photos' and is_allowed());
