-- Everything that happens, in one table: device heartbeats, book downloads,
-- sync runs, site actions, and errors. Services and devices insert with the
-- public key and nothing else; only allowed users read. An error becomes a
-- card on the board the first time its fingerprint is seen, and a count
-- afterwards, so two hundred tries of one broken book are one card.

alter table cards drop constraint if exists cards_source_check;
alter table cards add constraint cards_source_check
  check (source in ('session', 'site', 'import', 'github', 'error'));
alter table cards add column if not exists github_issue integer unique;
alter table cards add column if not exists fingerprint text;

create table if not exists events (
  id bigint generated by default as identity primary key,
  at timestamptz not null default now(),
  service text not null,                 -- firmware, getbooks, anki, instapaper, site, release
  event text not null,                   -- heartbeat, download, sync, install, report, error, ...
  level text not null default 'info' check (level in ('info', 'error')),
  device text,                           -- hashed device id, never the MAC
  version text,
  board text,                            -- x4pro, sticky
  props jsonb not null default '{}'::jsonb,
  fingerprint text,                      -- for errors: what makes two of them the same
  card_id bigint references cards (id) on delete set null
);
create index if not exists events_at on events (at desc);
create index if not exists events_service_event_at on events (service, event, at desc);
create index if not exists events_device_at on events (device, at desc) where device is not null;
create index if not exists events_fingerprint on events (fingerprint) where fingerprint is not null;

create table if not exists error_fingerprints (
  fingerprint text primary key,
  service text not null,
  message text not null default '',
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  count integer not null default 0,
  card_id bigint references cards (id) on delete set null
);

create extension if not exists pgcrypto with schema extensions;

-- The fingerprint, when the sender did not compute one: the service, the
-- event, and the message with numbers and hex stripped, so "book 4127 timed
-- out" and "book 9 timed out" are one problem.
create or replace function event_fingerprint(p_service text, p_event text, p_message text)
returns text language sql immutable as $$
  select encode(extensions.digest(
    p_service || '|' || p_event || '|' ||
    regexp_replace(lower(coalesce(p_message, '')), '[0-9a-f]{6,}|[0-9]+', '#', 'g'),
    'sha256'), 'hex')
$$;

create or replace function events_before_insert() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  fp text;
  msg text;
  open_card bigint;
  new_card bigint;
begin
  if new.level <> 'error' then
    return new;
  end if;
  msg := coalesce(new.props ->> 'message', '');
  fp := coalesce(new.fingerprint, event_fingerprint(new.service, new.event, msg));
  new.fingerprint := fp;

  insert into error_fingerprints (fingerprint, service, message, count, last_seen)
    values (fp, new.service, left(msg, 400), 1, now())
    on conflict (fingerprint) do update
      set count = error_fingerprints.count + 1, last_seen = now()
    returning card_id into open_card;

  -- One open card per fingerprint. A card that was closed and then the error
  -- came back gets a fresh card, because that is a regression, not a repeat.
  if open_card is not null then
    if exists (select 1 from cards where id = open_card and state not in ('done', 'released', 'parked')) then
      new.card_id := open_card;
      return new;
    end if;
  end if;

  insert into cards (title, app, kind, body, state, source, fingerprint)
    values (
      left(new.service || ': ' || coalesce(nullif(msg, ''), new.event), 120),
      new.service, 'bug',
      'Seen by the ' || new.service || ' service. First message: ' || left(msg, 1000) ||
        E'\nEvent: ' || new.event || E'\nProps: ' || left(new.props::text, 1500),
      'triaged', 'error', fp)
    returning id into new_card;
  insert into history (card_id, what) values (new_card, 'opened from an error event (' || new.service || ')');
  update error_fingerprints set card_id = new_card where fingerprint = fp;
  new.card_id := new_card;
  return new;
end
$$;
drop trigger if exists events_error_card on events;
create trigger events_error_card before insert on events
  for each row execute function events_before_insert();

-- The numbers Mario asks for.
create or replace view devices_by_version as
  select coalesce(board, 'unknown') as board, coalesce(version, 'unknown') as version,
         count(distinct device) as devices
  from events
  where event = 'heartbeat' and device is not null and at > now() - interval '7 days'
  group by 1, 2 order by 1, 2 desc;

create or replace view daily_active_devices as
  select date_trunc('day', at)::date as day, count(distinct device) as devices
  from events
  where event = 'heartbeat' and device is not null and at > now() - interval '30 days'
  group by 1 order by 1 desc;

create or replace view events_daily as
  select date_trunc('day', at)::date as day, service, event, level, count(*) as n
  from events
  where at > now() - interval '30 days'
  group by 1, 2, 3, 4 order by 1 desc, 2, 3;

create or replace view service_users as
  select service, count(distinct device) as devices_7d, count(*) as events_7d
  from events
  where at > now() - interval '7 days' and event <> 'heartbeat'
  group by 1 order by 1;

alter table events enable row level security;
alter table error_fingerprints enable row level security;

drop policy if exists events_insert_anyone on events;
create policy events_insert_anyone on events for insert to anon, authenticated with check (true);
drop policy if exists events_read_allowed on events;
create policy events_read_allowed on events for select to authenticated using (is_allowed());
drop policy if exists fingerprints_read_allowed on error_fingerprints;
create policy fingerprints_read_allowed on error_fingerprints for select to authenticated using (is_allowed());

-- Views run as their owner (postgres) by default; make them honour the
-- caller's row security so the anon key sees nothing through them.
alter view devices_by_version set (security_invoker = true);
alter view daily_active_devices set (security_invoker = true);
alter view events_daily set (security_invoker = true);
alter view service_users set (security_invoker = true);
alter view inbox set (security_invoker = true);
