#!/usr/bin/env python3
"""
Generate the CrossPlay mark: the on-device 1-bit bitmap and the vector beside it.

docs/identity.md fixes the mark as corner brackets around a screen, and fixes
site/assets/logo.svg as the drawing of record. This script is that same shape
expressed once, at the size the panel wants, so the device and the page cannot
drift apart by hand-editing.

It emits:
  src/images/logo.svg    the mark at the device's size, for anyone who needs it
                         as vector (a README, a mock-up)
  src/images/Logo120.h   the 120x120 1-bit array BootActivity and SleepActivity
                         draw
  src/images/Logo120.png the same pixels as RGBA, which is what the user guide
                         cover is built from (scripts/generate_userguide_epub.py)

Everything here is axis-aligned, so it is rasterised exactly rather than
thresholded from an anti-aliased render. That is deliberate: the panel is 1-bit
and a rasteriser's grey edge has nowhere to go. It also means the script needs
no PIL and no cairosvg, neither of which is installed anywhere in this project.

Usage: python3 scripts/generate_logo.py [--check]
       --check exits non-zero if the files on disk are not what this would write
"""

import os
import struct
import sys
import zlib

SIZE = 120

# The mark, in device pixels. site/assets/logo.svg draws it on a 32-unit
# viewBox; every number below is that drawing at 3.75x, rounded to whole pixels
# so no edge lands mid-pixel.
STROKE = 10  # 2.6 units
INSET = 5  # 2.6 units of centreline, minus half the stroke
ARM = 39  # 10.4 units: the 7.8 run plus a half stroke at BOTH ends --
          # the outer edge and the square linecap. Getting this wrong by one
          # half-stroke makes the device brackets stubbier than the site's.
BLOCK = 58  # 15.2 units
BLOCK_RADIUS = 6  # 1.6 units

BLOCK_X0 = (SIZE - BLOCK) // 2
BLOCK_X1 = BLOCK_X0 + BLOCK  # exclusive


def rects():
    """The mark as a list of (x0, y0, x1, y1) half-open rectangles."""
    out = []
    near = INSET
    far = SIZE - INSET - STROKE  # left edge of the right-hand stroke
    for x_corner in (near, far):
        for y_corner in (near, far):
            # The arm runs away from the corner, back towards the middle.
            x_arm = x_corner if x_corner == near else x_corner + STROKE - ARM
            y_arm = y_corner if y_corner == near else y_corner + STROKE - ARM
            # horizontal arm
            out.append((x_arm, y_corner, x_arm + ARM, y_corner + STROKE))
            # vertical arm
            out.append((x_corner, y_arm, x_corner + STROKE, y_arm + ARM))
    return out


def is_ink(x, y):
    """True where the mark is black."""
    for x0, y0, x1, y1 in rects():
        if x0 <= x < x1 and y0 <= y < y1:
            return True
    # The centre block, with rounded corners.
    if BLOCK_X0 <= x < BLOCK_X1 and BLOCK_X0 <= y < BLOCK_X1:
        r = BLOCK_RADIUS
        # Distance into the block from whichever corner is nearest.
        dx = min(x - BLOCK_X0, BLOCK_X1 - 1 - x)
        dy = min(y - BLOCK_X0, BLOCK_X1 - 1 - y)
        if dx < r and dy < r:
            # Sample the pixel's centre against the corner arc.
            ox, oy = (r - 0.5) - dx, (r - 0.5) - dy
            return ox * ox + oy * oy <= r * r
        return True
    return False


def header():
    """The 1-bit array, in the orientation the framebuffer wants.

    GfxRenderer reads these arrays a quarter turn from how they are seen: the
    CrossPoint logo this replaces was stored the same way, and decoding it is
    how the transform below was established. stored(a, b) is visible(H-1-b, a).
    Bits are MSB-first and 1 is WHITE, so the mark itself is the zeroes.
    """
    packed = []
    for b in range(SIZE):
        for a0 in range(0, SIZE, 8):
            byte = 0
            for i in range(8):
                a = a0 + i
                if not is_ink(SIZE - 1 - b, a):
                    byte |= 1 << (7 - i)
            packed.append(byte)

    out = "#pragma once\n#include <cstdint>\n\n"
    out += "// The CrossPlay mark: corner brackets around a screen (docs/identity.md).\n"
    out += "// Generated by scripts/generate_logo.py -- edit the script, not this file.\n"
    out += f"// Image dimensions: {SIZE}x{SIZE}\n"
    # Formatted the way clang-format would leave it: no trailing space at a line
    # break, and `};` closing the final value line. Emitting anything else means
    # the repo formatter rewrites this file and --check then calls it stale on
    # every run, with no state where both gates pass.
    rows = [packed[i : i + 19] for i in range(0, len(packed), 19)]
    body = "\n".join("    " + ", ".join(f"0x{v:02x}" for v in row) + "," for row in rows)
    out += "static const uint8_t Logo120[] = {\n" + body.rstrip(",") + "};\n"
    return out


def svg():
    near, far = INSET, SIZE - INSET - STROKE
    half = STROKE / 2
    paths = []
    for x_corner, xdir in ((near, 1), (far, -1)):
        for y_corner, ydir in ((near, 1), (far, -1)):
            cx = x_corner + half
            cy = y_corner + half
            run = ARM - STROKE
            paths.append(
                f'    <path d="M{cx:g} {cy + ydir * run:g}V{cy:g}h{xdir * run:g}" />'
            )
    body = "\n".join(paths)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" role="img" aria-label="CrossPlay">
  <title>CrossPlay</title>
  <!--
    The same mark as site/assets/logo.svg, drawn at the size the device panel
    uses so the vector and the 1-bit bitmap beside it are the one shape.

    Generated by scripts/generate_logo.py. Edit the script, not this file, and
    remember that site/assets/logo.svg and site/assets/favicon.svg carry the
    same shape off the device -- change one and change the others.
  -->
  <rect x="{BLOCK_X0}" y="{BLOCK_X0}" width="{BLOCK}" height="{BLOCK}" rx="{BLOCK_RADIUS}" fill="currentColor" />
  <g fill="none" stroke="currentColor" stroke-width="{STROKE}" stroke-linecap="square">
{body}
  </g>
</svg>
"""


def png():
    """The same pixels as RGBA: ink is opaque black, the rest is transparent.

    RGBA rather than 1-bit because generate_userguide_epub.py composites this
    over white through its alpha channel, and because that is what the file
    this replaces was. Hand-rolled on zlib because PIL is not installed here.
    """
    raw = bytearray()
    for y in range(SIZE):
        raw.append(0)  # PNG filter type 0 (None) for this scanline
        for x in range(SIZE):
            raw += b"\x00\x00\x00\xff" if is_ink(x, y) else b"\x00\x00\x00\x00"

    def chunk(tag, payload):
        body = tag + payload
        return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body))

    ihdr = struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0)  # 8-bit RGBA
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    targets = {
        os.path.join(root, "src", "images", "Logo120.h"): header().encode(),
        os.path.join(root, "src", "images", "logo.svg"): svg().encode(),
        os.path.join(root, "src", "images", "Logo120.png"): png(),
    }
    if "--check" in sys.argv[1:]:
        stale = [p for p, want in targets.items() if not os.path.exists(p) or open(p, "rb").read() != want]
        for p in stale:
            print(f"stale: {os.path.relpath(p, root)}", file=sys.stderr)
        if stale:
            print("run: python3 scripts/generate_logo.py", file=sys.stderr)
            return 1
        return 0
    for path, content in targets.items():
        with open(path, "wb") as f:
            f.write(content)
        print(f"wrote {os.path.relpath(path, root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
