#!/bin/bash
# Regenerate src/apps_local/jaipur/JaipurArt.h from assets_local/jaipur/.
#
#   brew install librsvg          # rsvg-convert, the only external dependency
#   ./tools_local/gen_jaipur_art.sh
#
# The output is committed, because regenerating needs librsvg and a checkout
# should build without it. Edit the SVGs, run this, commit both.
#
# The SDK's own icon generator, pointed at our SVG instead of Lucide's, the same
# way tools_local/gen_avatar.sh does. 32 is the shared shelf size, used by the
# pile and hand rows. 44 is the market card's, and it is 44 rather than 56
# because a 56 mark leaves a market card no room between itself and the price:
# measured on the panel, the mark sat 16px from the card's top edge and only
# 15px from the number under it.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
cd "$REPO"
# Two passes, because gen_icons.py takes one --svgdir and these have different
# provenance: the goods are Lucide's, the camel is ours. Two headers keeps that
# boundary visible rather than blending licensed art into hand-drawn.
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/jaipur_goods.txt \
  --svgdir freeink-sdk/libs/assets/Icons/lucide/icons \
  --sizes 32,44 \
  --out src/apps_local/jaipur/JaipurGoods.h
echo "wrote src/apps_local/jaipur/JaipurGoods.h"

uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/jaipur_art.txt \
  --svgdir assets_local/jaipur \
  --sizes 32,44 \
  --out src/apps_local/jaipur/JaipurArt.h

# The generator hardcodes "from Lucide SVGs" in its banner, which is a lie in
# this file. Asserted rather than sed'd blind: if the SDK reworks its banner
# this stops the build instead of leaving the wrong provenance behind.
OUT=src/apps_local/jaipur/JaipurArt.h
WRONG="// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit."
RIGHT="// Generated by tools_local/gen_jaipur_art.sh from assets_local/jaipur/*.svg. Do not edit."
grep -qF "$WRONG" "$OUT" || { echo "gen_icons.py banner changed; update gen_jaipur_art.sh" >&2; exit 1; }
uv run --quiet python -c "
import sys
path, wrong, right = sys.argv[1:4]
text = open(path).read()
assert text.count(wrong) == 1
open(path, 'w').write(text.replace(wrong, right))
" "$OUT" "$WRONG" "$RIGHT"

./bin/clang-format-fix >/dev/null 2>&1 || clang-format -i "$OUT"
echo "wrote $OUT"
