#!/usr/bin/env python3
"""The title fold, defined once, emitted for both sides.

docs/apps/wikipedia-pack-format.md, "Sort key: the fold":

  1. "_" becomes a space; runs of whitespace collapse to one; leading and
     trailing spaces go.
  2. ASCII letters lowercase.
  3. Code points in Latin-1 Supplement, Latin Extended-A and B (U+00C0 to
     U+024F), Greek (U+0370 to U+03FF) and Cyrillic (U+0400 to U+04FF) map
     through the table: accents stripped to the base letter, then lowercased.
  4. Everything else passes through unchanged.

The table is derived here from Unicode data (the first code point of the
NFKD decomposition, then casefold when that is one code point, else lower,
else the base itself), so "É" and "é" both become "e", "ß" stays "ß", "Ω"
becomes "ω", "ς" becomes "σ". Whitespace for rule 1 is the six ASCII
whitespace characters and "_", spelled out rather than str.isspace() so the
device can do exactly the same thing with no Unicode tables. A replacement
that is whitespace or a control is refused (the code point passes through
instead), so rule 3 can never undo rule 1; so is one that is longer in
UTF-8 than what it replaces, so a fold is never longer than its input.

    python3 tools_local/wikipedia/fold_table.py

writes, next to this file, fold.py (the Python fold) and fold_vectors.tsv
(300 input/expected pairs), and src/apps_local/wikipedia/WikipediaFold.h
(the device fold). All three are committed; regenerate after editing this
file and commit the result. The device test and tests/test_fold.py both
read the vectors, which is what proves the two sides agree.
"""

import os
import random
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
RANGES = ((0x00C0, 0x024F), (0x0370, 0x03FF), (0x0400, 0x04FF))
WHITESPACE = " \t\n\r\x0b\x0c_"
VECTOR_COUNT = 300


def derive(cp):
    """The replacement for one code point, or None when it passes through."""
    ch = chr(cp)
    base = unicodedata.normalize("NFKD", ch)[0]
    cand = base.casefold()
    if len(cand) != 1:
        cand = base.lower()
    if len(cand) != 1:
        cand = base
    if cand == ch:
        return None
    if cand.isspace() or unicodedata.category(cand)[0] == "C":
        return None
    if len(cand.encode()) > len(ch.encode()):
        # U+023A and U+023E lowercase into Latin Extended-C, three UTF-8
        # bytes for two. Passing them through keeps the guarantee the C++
        # side is built on: a fold is never longer than its input.
        return None
    return ord(cand)


def build_table():
    table = []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            r = derive(cp)
            if r is not None:
                table.append((cp, r))
    for cp, r in table:
        assert r < 0x10000, f"replacement for U+{cp:04X} is U+{r:04X}, outside the BMP"
        assert len(chr(r).encode()) <= len(chr(cp).encode()), (
            f"U+{cp:04X} -> U+{r:04X} grows in UTF-8; the C++ side assumes it never does"
        )
    return table


def fold_with(table_map, title):
    """The fold, written the way the C++ does it, so the vectors come from
    the same procedure the shipped module uses."""
    out = []
    pending = False
    for ch in title:
        if ch in WHITESPACE:
            if out:
                pending = True
            continue
        if pending:
            out.append(" ")
            pending = False
        o = ord(ch)
        if 0x41 <= o <= 0x5A:
            ch = chr(o + 32)
        elif o >= 0xC0:
            ch = table_map.get(ch, ch)
        out.append(ch)
    return "".join(out)


# --- fold.py -----------------------------------------------------------------
PY_HEAD = '''"""GENERATED by tools_local/wikipedia/fold_table.py; do not edit.

The title fold of docs/apps/wikipedia-pack-format.md. The same table is in
src/apps_local/wikipedia/WikipediaFold.h and fold_vectors.tsv proves the two
agree. Regenerate with: python3 tools_local/wikipedia/fold_table.py
"""

WHITESPACE = frozenset(%r)

'''

PY_TAIL = '''

def fold(title):
    """Sort and lookup key for a display title. Never longer, in UTF-8
    bytes, than its input."""
    out = []
    pending = False
    for ch in title:
        if ch in WHITESPACE:
            if out:
                pending = True
            continue
        if pending:
            out.append(" ")
            pending = False
        o = ord(ch)
        if 0x41 <= o <= 0x5A:
            ch = chr(o + 32)
        elif o >= 0xC0:
            ch = TABLE.get(ch, ch)
        out.append(ch)
    return "".join(out)


def fold_bytes(title):
    return fold(title).encode("utf-8")
'''


def emit_python(table, path):
    lines = [PY_HEAD % (WHITESPACE,), "TABLE = {"]
    for cp, r in table:
        lines.append(f'    "\\u{cp:04x}": "\\u{r:04x}",')
    lines.append("}")
    lines.append(PY_TAIL)
    with open(path, "w", encoding="ascii") as f:
        f.write("\n".join(lines))


# --- WikipediaFold.h ---------------------------------------------------------
CPP_HEAD = """// GENERATED by tools_local/wikipedia/fold_table.py; do not edit.
//
// The title fold of docs/apps/wikipedia-pack-format.md, "Sort key: the fold".
// tools_local/wikipedia/fold.py is the same procedure in Python and
// tools_local/wikipedia/fold_vectors.tsv proves the two agree. Regenerate
// with: python3 tools_local/wikipedia/fold_table.py
//
// Freestanding: no allocation, no <string>, no locale. The output is never
// longer than the input in bytes (every table replacement is at most as
// long in UTF-8 as the code point it replaces), so an output buffer the size
// of the input always suffices; a smaller one truncates at a character
// boundary and outLen says how much was written.
//
// clang-format off
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace wikipedia {
namespace fold_detail {

struct FoldPair {
  uint16_t from;
  uint16_t to;
};

// Sorted by `from`; every entry differs from its replacement.
inline constexpr FoldPair kTable[] = {
"""

CPP_TAIL = """};

inline constexpr size_t kTableSize = sizeof(kTable) / sizeof(kTable[0]);

inline bool inTableRange(uint32_t cp) {
  return (cp >= 0x00C0 && cp <= 0x024F) || (cp >= 0x0370 && cp <= 0x03FF) ||
         (cp >= 0x0400 && cp <= 0x04FF);
}

inline uint32_t lookup(uint32_t cp) {
  size_t lo = 0, hi = kTableSize;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (kTable[mid].from < cp) {
      lo = mid + 1;
    } else {
      hi = mid;
    }
  }
  if (lo < kTableSize && kTable[lo].from == cp) {
    return kTable[lo].to;
  }
  return cp;
}

// Decodes one UTF-8 sequence at in[i]. Returns its length, or 0 for a byte
// that starts no valid sequence (the caller copies that byte through).
inline size_t decode(const char* in, size_t inLen, size_t i, uint32_t* cp) {
  unsigned char c = static_cast<unsigned char>(in[i]);
  size_t n;
  uint32_t v;
  if (c < 0x80) {
    *cp = c;
    return 1;
  } else if ((c & 0xE0) == 0xC0) {
    n = 2;
    v = c & 0x1F;
  } else if ((c & 0xF0) == 0xE0) {
    n = 3;
    v = c & 0x0F;
  } else if ((c & 0xF8) == 0xF0) {
    n = 4;
    v = c & 0x07;
  } else {
    return 0;
  }
  if (i + n > inLen) {
    return 0;
  }
  for (size_t k = 1; k < n; k++) {
    unsigned char cc = static_cast<unsigned char>(in[i + k]);
    if ((cc & 0xC0) != 0x80) {
      return 0;
    }
    v = (v << 6) | (cc & 0x3F);
  }
  *cp = v;
  return n;
}

inline size_t encode(uint32_t cp, char* out, size_t cap) {
  if (cp < 0x80) {
    if (cap < 1) return 0;
    out[0] = static_cast<char>(cp);
    return 1;
  } else if (cp < 0x800) {
    if (cap < 2) return 0;
    out[0] = static_cast<char>(0xC0 | (cp >> 6));
    out[1] = static_cast<char>(0x80 | (cp & 0x3F));
    return 2;
  } else if (cp < 0x10000) {
    if (cap < 3) return 0;
    out[0] = static_cast<char>(0xE0 | (cp >> 12));
    out[1] = static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
    out[2] = static_cast<char>(0x80 | (cp & 0x3F));
    return 3;
  }
  if (cap < 4) return 0;
  out[0] = static_cast<char>(0xF0 | (cp >> 18));
  out[1] = static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
  out[2] = static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
  out[3] = static_cast<char>(0x80 | (cp & 0x3F));
  return 4;
}

inline bool isFoldSpace(uint32_t cp) {
  return cp == ' ' || cp == '_' || (cp >= 0x09 && cp <= 0x0D);
}

inline bool isAscii(const char* in, size_t inLen) {
  for (size_t i = 0; i < inLen; i++) {
    if (static_cast<unsigned char>(in[i]) >= 0x80) return false;
  }
  return true;
}

}  // namespace fold_detail

// Folds a display title into its sort and lookup key. `in` need not be
// NUL-terminated and `out` is not NUL-terminated; *outLen is the bytes
// written. Stops at a character boundary when `out` is full.
inline void foldTitle(const char* in, size_t inLen, char* out, size_t outCap, size_t* outLen) {
  using namespace fold_detail;
  size_t o = 0;
  bool pendingSpace = false;
  if (isAscii(in, inLen)) {
    // 92% of titles: lowercase and the whitespace rule, byte by byte.
    for (size_t i = 0; i < inLen; i++) {
      unsigned char c = static_cast<unsigned char>(in[i]);
      if (isFoldSpace(c)) {
        if (o > 0) pendingSpace = true;
        continue;
      }
      if (o + (pendingSpace ? 1 : 0) + 1 > outCap) break;
      if (pendingSpace) {
        out[o++] = ' ';
        pendingSpace = false;
      }
      out[o++] = (c >= 'A' && c <= 'Z') ? static_cast<char>(c + 32) : static_cast<char>(c);
    }
    *outLen = o;
    return;
  }
  size_t i = 0;
  while (i < inLen) {
    uint32_t cp;
    size_t n = decode(in, inLen, i, &cp);
    if (n == 0) {
      // Not UTF-8: pass the byte through untouched, like any other symbol.
      if (pendingSpace) {
        if (o + 1 > outCap) break;
        out[o++] = ' ';
        pendingSpace = false;
      }
      if (o + 1 > outCap) break;
      out[o++] = in[i];
      i += 1;
      continue;
    }
    if (isFoldSpace(cp)) {
      if (o > 0) pendingSpace = true;
      i += n;
      continue;
    }
    if (cp >= 'A' && cp <= 'Z') {
      cp += 32;
    } else if (inTableRange(cp)) {
      cp = lookup(cp);
    }
    size_t need = (cp < 0x80) ? 1 : (cp < 0x800) ? 2 : (cp < 0x10000) ? 3 : 4;
    if (o + (pendingSpace ? 1 : 0) + need > outCap) break;
    if (pendingSpace) {
      out[o++] = ' ';
      pendingSpace = false;
    }
    o += encode(cp, out + o, outCap - o);
    i += n;
  }
  *outLen = o;
}

}  // namespace wikipedia
"""


def emit_cpp(table, path):
    lines = [CPP_HEAD]
    row = []
    for cp, r in table:
        row.append(f"{{0x{cp:04X}, 0x{r:04X}}}")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append(CPP_TAIL)
    with open(path, "w", encoding="ascii") as f:
        f.write("\n".join(lines))


# --- fold_vectors.tsv --------------------------------------------------------
ASCII_TITLES = [
    "Earth",
    "New York City",
    "Photosynthesis",
    "List of films: B",
    "C++",
    "AC/DC",
    "Hillary Clinton as Secretary of State",
    "1980s",
    "Anti-Catholicism",
    "O'Neill",
    "Ac",
    "AC",
    "aC",
    "Deaths in April 2026",
    "X-ray",
    "Mr. Bean",
    "100% (song)",
    "Q",
    "q",
    "A",
    "The Beatles",
    "THE BEATLES",
    "the beatles",
    "Rock 'n' roll",
    "F.C. Barcelona",
    "S.H.I.E.L.D.",
    "Bo Diddley (album)",
    "2001: A Space Odyssey",
    "Hello, World!",
    "K-pop",
    "ABBA",
    "iPhone",
    "eBay",
    "NASA",
    "U.S. Route 66",
    "Tracey Ullman's State of the Union characters",
    "Slam dunk",
    "Saving Abel",
    "Yascha Mounk",
    "Zzyzx, California",
]
UNDERSCORE_TITLES = [
    "New_York_City",
    "List_of_films:_B",
    "__leading",
    "trailing__",
    "a__b",
    "_",
    "__",
    "a_",
    "_a",
    "one_two_three",
    "New York_City",
    "Mr._Bean",
]
SPACE_TITLES = [
    "  New York",
    "New York  ",
    "New  York",
    "New   York   City",
    " ",
    "  ",
    "",
    "\tTabbed\tTitle\t",
    "Line\nbreak",
    "Carriage\rreturn",
    "Form\x0cfeed",
    "Vertical\x0btab",
    " _ _ _ ",
    "A _ B",
    "\t_\t",
]
ACCENT_TITLES = [
    "Mágico González",
    "Łatwogang",
    "Senate district 56 – Břeclav",
    "Jan Małachowski (Grand Chancellor of the Crown)",
    "École normale supérieure",
    "Ærø",
    "Øresund",
    "Đà Nẵng",
    "Straße",
    "STRASSE",
    "Ångström",
    "Çatalhöyük",
    "İstanbul",
    "Istanbul",
    "Ĳssel",
    "IJssel",
    "Ñandú",
    "Þórr",
    "Ð",
    "ð",
    "ß",
    "Émile Zola",
    "émile zola",
    "ÉMILE ZOLA",
    "Kraków",
    "Kraków_Old_Town",
    "Zürich",
    "Zurich",
    "Ōkuma Shigenobu",
    "São Paulo",
    "Sao Paulo",
    "Tōkyō",
    "Đorđe",
    "Ǆ",
    "ǆ",
    "Ǉubljana",
    "Ŀ",
    "ŉ",
    "Ħal Tarxien",
    "Ŧ",
    "ơ",
    "Ơ",
    "Ư",
    "ư",
    "Ǝ",
    "ƒ",
    "Ɔ",
    "Ǻ",
    "Ǽ",
    "Ǿ",
    "ȷ",
    "Ȼ",
    "ɏ",
]
GREEK_TITLES = [
    "Ω",
    "ω",
    "Ωμέγα",
    "Αθήνα",
    "ΑΘΗΝΑ",
    "Οδυσσεύς",
    "ς",
    "σ",
    "Σ",
    "Ελληνικά",
    "Ἀθῆναι",
    "ϴ",
    "ϑ",
    "ϒ",
    "ϰ",
    "ΐ",
    "ΰ",
    "Ά",
    "ά",
    "Έ",
    "Greek: Ελλάδα",
    "ΆΈΉΊΌΎΏ",
    "άέήίόύώ",
]
CYRILLIC_TITLES = [
    "Москва",
    "МОСКВА",
    "москва",
    "Ёлка",
    "ёлка",
    "Йорк",
    "йорк",
    "Ѐ",
    "Ї",
    "Київ",
    "Санкт-Петербург",
    "Ђ",
    "ђ",
    "Љ",
    "Њ",
    "Џ",
    "Ӑ",
    "ӑ",
    "Ӓ",
    "Ӝ",
    "Ұ",
    "Ғ",
    "Қ",
    "Ө",
    "Ү",
    "Һ",
    "Ә",
    "Ӏ",
    "Ѣ",
    "ѣ",
    "Ѫ",
    "Russian: Россия",
    "Война и мир",
    "ВОЙНА И МИР",
]
PASSTHROUGH_TITLES = [
    "東京",
    "叔叔",
    "日本語",
    "Tokyo (東京)",
    "한국어",
    "עברית",
    "العربية",
    "हिन्दी",
    "ไทย",
    "Ελληνικά and 日本語",
    "Ａｂｃ",
    "Ⅻ",
    "ǅ日本",
    "ﬁ",
    "ẞ",
    "ẞ and ß",
    "Ḃ",
    "ḃ",
    "Ẽ",
    "ᴀ",
    "ⓐ",
    "Ⓐ",
    "Ａ",
    "🙂",
    "Ａ_Ｂ",
    "北京_市",
    "中文 維基百科",
    "ǅ",
    "Ａ  Ｂ",
]
FUNNY = [
    "AbC_DeF  ГдЕ  ΘιΚ  日本",
    "  _É_  ",
    "É",
    "É_",
    "_É",
    "é_É",
    "  Ω  Ω  ",
    "\u00a0NBSP\u00a0kept",
    "A\u00a0B",
    "en dash – kept",
    "Q-tip",
    "x_y-z",
]


def unescape_tsv(s):
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            out.append(
                {
                    "t": "\t",
                    "n": "\n",
                    "r": "\r",
                    "\\": "\\",
                    "f": "\x0c",
                    "v": "\x0b",
                }.get(n, n)
            )
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def escape_tsv(s):
    return (
        s.replace("\\", "\\\\")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\x0c", "\\f")
        .replace("\x0b", "\\v")
    )


def make_vectors(table):
    table_map = {chr(a): chr(b) for a, b in table}
    inputs = []
    for group in (
        ASCII_TITLES,
        UNDERSCORE_TITLES,
        SPACE_TITLES,
        ACCENT_TITLES,
        GREEK_TITLES,
        CYRILLIC_TITLES,
        PASSTHROUGH_TITLES,
        FUNNY,
    ):
        inputs.extend(group)
    seen = set(inputs)
    assert len(seen) == len(inputs), "duplicate hand-written vector"
    # Fill to VECTOR_COUNT with seeded random titles built from table
    # entries, ASCII words and passthrough scripts, so every table range is
    # exercised beyond the hand-picked names.
    rng = random.Random(20260911)
    words = ["Alpha", "beta", "GAMMA", "delta", "Epsilon", "zeta", "eta", "THETA"]
    cps = [chr(a) for a, _ in table]
    extra = ["日", "本", "語", "京", "한", "글", "ع", "ب"]
    while len(inputs) < VECTOR_COUNT:
        parts = []
        for _ in range(rng.randint(1, 5)):
            kind = rng.random()
            if kind < 0.4:
                parts.append(rng.choice(words))
            elif kind < 0.8:
                parts.append("".join(rng.choice(cps) for _ in range(rng.randint(1, 4))))
            elif kind < 0.9:
                parts.append(
                    "".join(rng.choice(extra) for _ in range(rng.randint(1, 3)))
                )
            else:
                parts.append(rng.choice(["_", "  ", "\t", " _ "]))
        s = rng.choice(["", " ", "_"]).join(parts)
        if s in seen:
            continue
        seen.add(s)
        inputs.append(s)
    assert len(inputs) == VECTOR_COUNT
    return [(s, fold_with(table_map, s)) for s in inputs]


def emit_vectors(vectors, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write("# GENERATED by tools_local/wikipedia/fold_table.py; do not edit.\n")
        f.write(
            "# input<TAB>expected, one per line; \\t \\n \\r \\f \\v \\\\ escape the\n"
        )
        f.write("# characters they name. Lines starting with # are comments.\n")
        for s, e in vectors:
            f.write(f"{escape_tsv(s)}\t{escape_tsv(e)}\n")


def load_vectors(path):
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                continue
            line = line.rstrip("\n")
            if not line:
                continue
            a, b = line.split("\t")
            out.append((unescape_tsv(a), unescape_tsv(b)))
    return out


def main():
    table = build_table()
    emit_python(table, os.path.join(HERE, "fold.py"))
    cpp_dir = os.path.join(REPO, "src", "apps_local", "wikipedia")
    os.makedirs(cpp_dir, exist_ok=True)
    emit_cpp(table, os.path.join(cpp_dir, "WikipediaFold.h"))
    vectors = make_vectors(table)
    emit_vectors(vectors, os.path.join(HERE, "fold_vectors.tsv"))
    print(f"table entries: {len(table)}; vectors: {len(vectors)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
